<?php
// This script and data application were generated by AppGini 4.2 on 1/14/2009 at 11:53:44 AM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/defaultLang.php");
	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/stockitems_dml.php");

	// SQL query used in the filters page and the CSV file
	$filtersCSVQuery="select stockitems.ID as 'ID', stockitems.Name as 'Name', stockitems.ItemDescription as 'ItemDescription', stockitems.suggestedvalue as 'suggestedvalue', stockitems.Cost as 'Cost' from stockitems ";
	// SQL query used in the table view
	$tableViewQuery="select stockitems.ID as 'ID', stockitems.Name as 'Name', stockitems.ItemDescription as 'ItemDescription', stockitems.suggestedvalue as 'suggestedvalue', stockitems.Cost as 'Cost' from stockitems ";

	// mm: can the current member access this page?
	$perm=getTablePermissions('stockitems');
	if(!$perm[0]){
		echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		exit;
	}

	$x = new DataList;
	$x->TableName = "stockitems";
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "stockitems_view.php";
	$x->RedirectAfterInsert = "stockitems_view.php?SelectedID=#ID#";
	$x->TableTitle = "stockitems";
	$x->PrimaryKey = "stockitems.ID";

	$x->ColWidth   = array(150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "Name", "ItemDescription", "suggestedvalue", "Cost");
	$x->ColNumber  = array(1, 2, 3, 4, 5);

	$x->Template = 'stockitems_templateTV.html';
	$x->SelectedTemplate = 'stockitems_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != ""){
		// Query used in filters page and CSV output
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where stockitems.ID=membership_userrecords.pkValue and membership_userrecords.tableName='stockitems' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where stockitems.ID=membership_userrecords.pkValue and membership_userrecords.tableName='stockitems' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $filtersCSVQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from stockitems";
		}
	}else{
		// Query used in table view
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $tableViewQuery.", membership_userrecords  where stockitems.ID=membership_userrecords.pkValue and membership_userrecords.tableName='stockitems' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $tableViewQuery.", membership_userrecords  where stockitems.ID=membership_userrecords.pkValue and membership_userrecords.tableName='stockitems' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $tableViewQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from stockitems";
		}
	}

	// handle date sorting correctly
	// end of date sorting handler


	$x->Render();

	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?><center><font size=-2><?php echo $Translation["powered by"]; ?> <a href=http://www.bigprof.com/appgini>AppGini 4.2</a></font></center>
