<?php

// Data functions for table contacts

// This script and data application were generated by AppGini 4.2 on 1/15/2009 at 3:25:27 AM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert(){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;

	if($HTTP_GET_VARS['insert_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('contacts');
	if(!$arrPerm[1]){
		return 0;
	}

	$contact_chamberid = makeSafe($HTTP_POST_VARS["contact_chamberid"]);
	$contact_name = makeSafe($HTTP_POST_VARS["contact_name"]);
	$contact_type = makeSafe($HTTP_POST_VARS["contact_type"]);
	$contact_primary = makeSafe($HTTP_POST_VARS["contact_primary"]);
	$contact_secondary = makeSafe($HTTP_POST_VARS["contact_secondary"]);
	$contact_address = makeSafe($HTTP_POST_VARS["contact_address"]);
	$contact_city = makeSafe($HTTP_POST_VARS["contact_city"]);
	$contact_state = makeSafe($HTTP_POST_VARS["contact_state"]);
	$contact_zip = makeSafe($HTTP_POST_VARS["contact_zip"]);
	$contact_phone = makeSafe($HTTP_POST_VARS["contact_phone"]);
	$contact_email = makeSafe($HTTP_POST_VARS["contact_email"]);
	$contact_dns = makeSafe($HTTP_POST_VARS["contact_dns"]);
	$contact_lastyear = makeSafe($HTTP_POST_VARS["contact_lastyear"]);
	$contact_advertisements = makeSafe($HTTP_POST_VARS["contact_advertisements"]);
	$contact_comments = makeSafe($HTTP_POST_VARS["contact_comments"]);
	$rotarian_id = makeSafe($HTTP_POST_VARS["rotarian_id"]);
	if($contact_name== ""){
		echo StyleSheet() . "\n\n<div class=Error>" . $Translation["error:"] . " 'Name': " . $Translation['field not null'] . "</div>";
		exit;
	}
	if($contact_city == "") $contact_city = "Washington";
	if($contact_state == "") $contact_state = "MO";
	if($contact_zip == "") $contact_zip = "63090";

	sql("insert into contacts (contact_chamberid, contact_name, contact_type, contact_primary, contact_secondary, contact_address, contact_city, contact_state, contact_zip, contact_phone, contact_email, contact_dns, contact_lastyear, contact_advertisements, contact_comments, rotarian_id) values (" . (($contact_chamberid != "") ? "'$contact_chamberid'" : "NULL") . ", " . (($contact_name != "") ? "'$contact_name'" : "NULL") . ", " . (($contact_type != "") ? "'$contact_type'" : "NULL") . ", " . (($contact_primary != "") ? "'$contact_primary'" : "NULL") . ", " . (($contact_secondary != "") ? "'$contact_secondary'" : "NULL") . ", " . (($contact_address != "") ? "'$contact_address'" : "NULL") . ", " . (($contact_city != "") ? "'$contact_city'" : "NULL") . ", " . (($contact_state != "") ? "'$contact_state'" : "NULL") . ", " . (($contact_zip != "") ? "'$contact_zip'" : "NULL") . ", " . (($contact_phone != "") ? "'$contact_phone'" : "NULL") . ", " . (($contact_email != "") ? "'$contact_email'" : "NULL") . ", " . (($contact_dns != "") ? "'$contact_dns'" : "NULL") . ", " . (($contact_lastyear != "") ? "'$contact_lastyear'" : "NULL") . ", " . (($contact_advertisements != "") ? "'$contact_advertisements'" : "NULL") . ", " . (($contact_comments != "") ? "'$contact_comments'" : "NULL") . ", " . (($rotarian_id != "") ? "'$rotarian_id'" : "NULL") . ")");
	// mm: save ownership data
	$recID=mysql_insert_id();
	sql("insert into membership_userrecords set tableName='contacts', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'");

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	// mm: can member delete record?
	$arrPerm=getTablePermissions('contacts');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return FALSE;
	}

	// child table: donations
	$res = sql("select id from contacts where id='".makeSafe($selected_id)."'");
	$id = mysql_fetch_row($res);
	$rires = sql("select count(1) from donations where contact_id='".addslashes($id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='contacts_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='contacts_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}


	sql("delete from contacts where id='".makeSafe($selected_id)."'");

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
}

function update($selected_id){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;

	if($HTTP_GET_VARS['update_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('contacts');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return;
	}

	if(get_magic_quotes_gpc()){
		$contact_chamberid = $HTTP_POST_VARS["contact_chamberid"];
		$contact_name = $HTTP_POST_VARS["contact_name"];
		$contact_type = $HTTP_POST_VARS["contact_type"];
		$contact_primary = $HTTP_POST_VARS["contact_primary"];
		$contact_secondary = $HTTP_POST_VARS["contact_secondary"];
		$contact_address = $HTTP_POST_VARS["contact_address"];
		$contact_city = $HTTP_POST_VARS["contact_city"];
		$contact_state = $HTTP_POST_VARS["contact_state"];
		$contact_zip = $HTTP_POST_VARS["contact_zip"];
		$contact_phone = $HTTP_POST_VARS["contact_phone"];
		$contact_email = $HTTP_POST_VARS["contact_email"];
		$contact_dns = $HTTP_POST_VARS["contact_dns"];
		$contact_lastyear = $HTTP_POST_VARS["contact_lastyear"];
		$contact_advertisements = $HTTP_POST_VARS["contact_advertisements"];
		$contact_comments = $HTTP_POST_VARS["contact_comments"];
		$rotarian_id = $HTTP_POST_VARS["rotarian_id"];
	}else{
		$contact_chamberid = addslashes($HTTP_POST_VARS["contact_chamberid"]);
		$contact_name = addslashes($HTTP_POST_VARS["contact_name"]);
		$contact_type = addslashes($HTTP_POST_VARS["contact_type"]);
		$contact_primary = addslashes($HTTP_POST_VARS["contact_primary"]);
		$contact_secondary = addslashes($HTTP_POST_VARS["contact_secondary"]);
		$contact_address = addslashes($HTTP_POST_VARS["contact_address"]);
		$contact_city = addslashes($HTTP_POST_VARS["contact_city"]);
		$contact_state = addslashes($HTTP_POST_VARS["contact_state"]);
		$contact_zip = addslashes($HTTP_POST_VARS["contact_zip"]);
		$contact_phone = addslashes($HTTP_POST_VARS["contact_phone"]);
		$contact_email = addslashes($HTTP_POST_VARS["contact_email"]);
		$contact_dns = addslashes($HTTP_POST_VARS["contact_dns"]);
		$contact_lastyear = addslashes($HTTP_POST_VARS["contact_lastyear"]);
		$contact_advertisements = addslashes($HTTP_POST_VARS["contact_advertisements"]);
		$contact_comments = addslashes($HTTP_POST_VARS["contact_comments"]);
		$rotarian_id = addslashes($HTTP_POST_VARS["rotarian_id"]);
	}

	sql("update contacts set " . "contact_chamberid=" . (($contact_chamberid != "") ? "'$contact_chamberid'" : "NULL") . ", " . "contact_name=" . (($contact_name != "") ? "'$contact_name'" : "NULL") . ", " . "contact_type=" . (($contact_type != "") ? "'$contact_type'" : "NULL") . ", " . "contact_primary=" . (($contact_primary != "") ? "'$contact_primary'" : "NULL") . ", " . "contact_secondary=" . (($contact_secondary != "") ? "'$contact_secondary'" : "NULL") . ", " . "contact_address=" . (($contact_address != "") ? "'$contact_address'" : "NULL") . ", " . "contact_city=" . (($contact_city != "") ? "'$contact_city'" : "NULL") . ", " . "contact_state=" . (($contact_state != "") ? "'$contact_state'" : "NULL") . ", " . "contact_zip=" . (($contact_zip != "") ? "'$contact_zip'" : "NULL") . ", " . "contact_phone=" . (($contact_phone != "") ? "'$contact_phone'" : "NULL") . ", " . "contact_email=" . (($contact_email != "") ? "'$contact_email'" : "NULL") . ", " . "contact_dns=" . (($contact_dns != "") ? "'$contact_dns'" : "NULL") . ", " . "contact_lastyear=" . (($contact_lastyear != "") ? "'$contact_lastyear'" : "NULL") . ", " . "contact_advertisements=" . (($contact_advertisements != "") ? "'$contact_advertisements'" : "NULL") . ", " . "contact_comments=" . (($contact_comments != "") ? "'$contact_comments'" : "NULL") . ", " . "rotarian_id=" . (($rotarian_id != "") ? "'$rotarian_id'" : "NULL") . " where id='".makeSafe($selected_id)."'");

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");

}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;


	// mm: get table permissions
	$arrPerm=getTablePermissions('contacts');
	if(!$arrPerm[1] && $selected_id==""){ return ""; }
	// combobox: contact_type
	$combo_contact_type = new Combo;
	$combo_contact_type->ListType = 0;
	$combo_contact_type->ListBoxHeight = 10;
	$combo_contact_type->RadiosPerLine = 1;
	$combo_contact_type->ListItem = explode(";;", "Realty;;Doctor;;CPA;;Seq;;Esq;;Insurance;;Personal");
	$combo_contact_type->ListData = explode(";;", "Realty;;Doctor;;CPA;;Seq;;Esq;;Insurance;;Personal");
	$combo_contact_type->SelectName = "contact_type";
	// combobox: contact_state
	$combo_contact_state = new Combo;
	$combo_contact_state->ListType = 0;
	$combo_contact_state->ListBoxHeight = 10;
	$combo_contact_state->RadiosPerLine = 1;
	$combo_contact_state->ListItem = explode(";;", "AL;;AK;;AS;;AZ;;AR;;CA;;CO;;CT;;DE;;DC;;FM;;FL;;GA;;GU;;HI;;ID;;IL;;IN;;IA;;KS;;KY;;LA;;ME;;MH;;MD;;MA;;MI;;MN;;MS;;MO;;MT;;NE;;NV;;NH;;NJ;;NM;;NY;;NC;;ND;;MP;;OH;;OK;;OR;;PW;;PA;;PR;;RI;;SC;;SD;;TN;;TX;;UT;;VT;;VI;;VA;;WA;;WV;;WI;;WY");
	$combo_contact_state->ListData = explode(";;", "AL;;AK;;AS;;AZ;;AR;;CA;;CO;;CT;;DE;;DC;;FM;;FL;;GA;;GU;;HI;;ID;;IL;;IN;;IA;;KS;;KY;;LA;;ME;;MH;;MD;;MA;;MI;;MN;;MS;;MO;;MT;;NE;;NV;;NH;;NJ;;NM;;NY;;NC;;ND;;MP;;OH;;OK;;OR;;PW;;PA;;PR;;RI;;SC;;SD;;TN;;TX;;UT;;VT;;VI;;VA;;WA;;WV;;WI;;WY");
	$combo_contact_state->SelectName = "contact_state";
	// combobox: contact_dns
	$combo_contact_dns = new Combo;
	$combo_contact_dns->ListType = 2;
	$combo_contact_dns->ListBoxHeight = 10;
	$combo_contact_dns->RadiosPerLine = 1;
	$combo_contact_dns->ListItem = explode(";;", "Yes;;No");
	$combo_contact_dns->ListData = explode(";;", "Yes;;No");
	$combo_contact_dns->SelectName = "contact_dns";
	// combobox: contact_lastyear
	$combo_contact_lastyear = new Combo;
	$combo_contact_lastyear->ListType = 2;
	$combo_contact_lastyear->ListBoxHeight = 10;
	$combo_contact_lastyear->RadiosPerLine = 1;
	$combo_contact_lastyear->ListItem = explode(";;", "Yes;;No");
	$combo_contact_lastyear->ListData = explode(";;", "Yes;;No");
	$combo_contact_lastyear->SelectName = "contact_lastyear";
	// combobox: rotarian_id
	$combo_rotarian_id = new DataCombo;
	$combo_rotarian_id->Query = "select id, concat(rotarian_name, '::', id) from rotarians order by 2";
	$combo_rotarian_id->SelectName = "rotarian_id";

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='contacts' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		$res = sql("select * from contacts where id='".makeSafe($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_contact_type->SelectedData = $row["contact_type"];
		$combo_contact_state->SelectedData = $row["contact_state"];
		$combo_contact_dns->SelectedData = $row["contact_dns"];
		$combo_contact_lastyear->SelectedData = $row["contact_lastyear"];
		$combo_rotarian_id->SelectedData = $row["rotarian_id"];
	}else{
		$combo_contact_type->SelectedData = ( $_REQUEST['FilterField'][1]=='contacts.contact_type' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_contact_state->SelectedData = ( $_REQUEST['FilterField'][1]=='contacts.contact_state' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "MO");
		$combo_contact_dns->SelectedData = ( $_REQUEST['FilterField'][1]=='contacts.contact_dns' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_contact_lastyear->SelectedData = ( $_REQUEST['FilterField'][1]=='contacts.contact_lastyear' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_rotarian_id->SelectedData = ( $_REQUEST['FilterField'][1]=='contacts.rotarian_id' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_contact_type->Render();
	$combo_contact_state->Render();
	$combo_contact_dns->Render();
	$combo_contact_lastyear->Render();
	$combo_rotarian_id->Render();

	// code for template based detail view forms

	// open the detail view template
	$templateCode=@implode('', @file('./contacts_templateDV.html'));

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

			// set records to read only if user can't insert new records
			if(!$arrPerm[1]){
				$jsReadOnly.="\n\n\tif(document.getElementsByName('id').length){ document.getElementsByName('id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_chamberid').length){ document.getElementsByName('contact_chamberid')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_name').length){ document.getElementsByName('contact_name')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_type').length){ var contact_type=document.getElementsByName('contact_type')[0]; contact_type.disabled=true; contact_type.style.backgroundColor='white'; contact_type.style.color='black'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_primary').length){ document.getElementsByName('contact_primary')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_secondary').length){ document.getElementsByName('contact_secondary')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_address').length){ document.getElementsByName('contact_address')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_city').length){ document.getElementsByName('contact_city')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_state').length){ var contact_state=document.getElementsByName('contact_state')[0]; contact_state.disabled=true; contact_state.style.backgroundColor='white'; contact_state.style.color='black'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_zip').length){ document.getElementsByName('contact_zip')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_phone').length){ document.getElementsByName('contact_phone')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_email').length){ document.getElementsByName('contact_email')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_dns').length){ var contact_dns=document.getElementsByName('contact_dns'); for(var i=0; i<contact_dns.length; i++){ contact_dns[i].disabled=true; } }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_lastyear').length){ var contact_lastyear=document.getElementsByName('contact_lastyear'); for(var i=0; i<contact_lastyear.length; i++){ contact_lastyear[i].disabled=true; } }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_advertisements').length){ document.getElementsByName('contact_advertisements')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_comments').length){ document.getElementsByName('contact_comments')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('rotarian_id').length){ var rotarian_id=document.getElementsByName('rotarian_id')[0]; rotarian_id.disabled=true; rotarian_id.style.backgroundColor='white'; rotarian_id.style.color='black'; }\n";

				$noUploads=true;
			}
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? "<input type=image src=cancel.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>" : ''), $templateCode);
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(contact_type)%%>', $combo_contact_type->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(contact_type)%%>', $combo_contact_type->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(contact_state)%%>', $combo_contact_state->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(contact_state)%%>', $combo_contact_state->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(contact_dns)%%>', $combo_contact_dns->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(contact_dns)%%>', $combo_contact_dns->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(contact_lastyear)%%>', $combo_contact_lastyear->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(contact_lastyear)%%>', $combo_contact_lastyear->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(rotarian_id)%%>', $combo_rotarian_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(rotarian_id)%%>', $combo_rotarian_id->MatchText, $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(rotarian_id)%%>', ($combo_rotarian_id->SelectedData ? "<span id=rotarians_plink style=\"visibility: hidden;\"><a href=rotarians_view.php?SelectedID=".$combo_rotarian_id->SelectedData."><img border=0 src=lookup.gif></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_chamberid)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_type)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_primary)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_secondary)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_address)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_city)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_state)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_zip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_phone)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_email)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_dns)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_lastyear)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_advertisements)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_comments)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(rotarian_id)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_chamberid)%%>', htmlspecialchars($row['contact_chamberid'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name)%%>', htmlspecialchars($row['contact_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_type)%%>', htmlspecialchars($row['contact_type'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_primary)%%>', htmlspecialchars($row['contact_primary'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_secondary)%%>', htmlspecialchars($row['contact_secondary'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_address)%%>', htmlspecialchars($row['contact_address'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_city)%%>', htmlspecialchars($row['contact_city'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_state)%%>', htmlspecialchars($row['contact_state'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_zip)%%>', htmlspecialchars($row['contact_zip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_phone)%%>', htmlspecialchars($row['contact_phone'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_email)%%>', htmlspecialchars($row['contact_email'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_dns)%%>', htmlspecialchars($row['contact_dns'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%CHECKED(contact_lastyear)%%>', ($row['contact_lastyear'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_advertisements)%%>', htmlspecialchars($row['contact_advertisements'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_comments)%%>', htmlspecialchars($row['contact_comments'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(rotarian_id)%%>', htmlspecialchars($row['rotarian_id'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_chamberid)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_type)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_primary)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_secondary)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_address)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_city)%%>', 'Washington', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_state)%%>', 'MO', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_zip)%%>', '63090', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_phone)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_dns)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(contact_lastyear)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_advertisements)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_comments)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(rotarian_id)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);
	// hide links to inaccessible tables
	$templateCode.="\n\n<script>\n";
	$arrTables=getTableList();
	foreach($arrTables as $name=>$caption){
		$templateCode.="\tif(document.getElementById('".$name."_link')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_link').style.visibility='visible';\n";
		$templateCode.="\t}\n";
		$templateCode.="\tif(document.getElementById('".$name."_plink')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_plink').style.visibility='visible';\n";
		$templateCode.="\t}\n";
	}

	$templateCode.=$jsReadOnly;

	$templateCode.="\n</script>\n";


	// ajaxed auto-fill fields
	$templateCode.="<script src=\"prototype.js\"></script>";
	$templateCode.="<script>";
	$templateCode.="window.onload=function(){";


	$templateCode.="}";
	$templateCode.="</script>";

	return $templateCode;
}
?>