<?php
// This script and data application were generated by AppGini 4.2 on 1/15/2009 at 3:25:27 AM
// Download AppGini for free from http://www.bigprof.com/appgini/download/


error_reporting(E_ALL ^ E_NOTICE);
set_magic_quotes_runtime(0);
if(is_array($_POST)){
	$HTTP_POST_VARS=$_POST;
}
if(is_array($_GET)){
	$HTTP_GET_VARS=$_GET;
}
if(is_array($_FILES)){
	$HTTP_POST_FILES=$_FILES;
}

if(!@is_file(dirname(__FILE__)."/config.php")){
	echo StyleSheet() . "\n\n<div class=Error>";
	echo $Translation["error:"].' ';
	echo $Translation["if you haven't set up"];
	echo "</div>";
	exit;
}

include(dirname(__FILE__)."/config.php");
include(dirname(__FILE__)."/incCommon.php");
include(dirname(__FILE__)."/datalist.php");
function sql($statment,$assoc=1){

	global $Translation;
	global $dbServer, $dbUsername, $dbPassword, $dbDatabase;

		/****** Connect to MySQL ******/
		if(!extension_loaded('mysql')){
			echo "<div class=Error>ERROR: PHP is not configured to connect to MySQL on this machine. Please see <a href=http://www.php.net/manual/en/ref.mysql.php>this page</a> for help on how to configure MySQL.</div>";
			exit;
		}

		if(!mysql_connect($dbServer, $dbUsername, $dbPassword)){
			echo StyleSheet() . "\n\n<div class=Error>";
			echo $Translation["error:"] . mysql_error();
			echo "</div>";
			exit;
		}
		/****** Select DB ********/
		if(!mysql_select_db($dbDatabase)){
			echo StyleSheet() . "\n\n<div class=Error>";
			echo $Translation["error:"] . mysql_error();
			echo $Translation["if you haven't set up"];
			echo "</div>";
			exit;
		}

	if(!$result = @mysql_query($statment)){
		if(!stristr($statment, "show columns")){
			echo StyleSheet() . "\n\n<div class=Error>";
			echo "<br><b>" . $Translation["sql error:"] . "</b><br><br><strong>" . $Translation["query:"] . "</strong><br> $statment<br><br>" . mysql_error();
			if(stristr($statment, "select ")) echo ".<br>" . $Translation["if you haven't set up"];
			echo "</div>";
			echo "<a href=\"javascript:history.go(-1);\">" . $Translation["< back"] . "</a>";
			exit;
		}
	}
	return $result;
}

function NavMenus(){
	global $Translation;

	$t = time();
	$menu  = "<select name=nav_menu onChange='window.location=document.myform.nav_menu.options[document.myform.nav_menu.selectedIndex].value;'>";
	$menu .= "<option value='#' class=SelectedOption style='color:black;'>" . $Translation["select a table"] . "</option>";
	$menu .= "<option value='index.php' class=SelectedOption style='color:black;'>" . $Translation["homepage"] . "</option>";
	if(getLoggedAdmin()){
		$menu .= "<option value='admin/' class=SelectedOption style='color:red;'>" . $Translation['admin area'] . "</option>";
	}
	$arrTables=getTableList();
	if(is_array($arrTables)){
		foreach($arrTables as $tn=>$tc){
			$menu .= "<option value='".$tn."_view.php?t=$t' class=SelectedOption>$tc</option>";
		}
	}
	$menu .= "</select>";
	return $menu;
}

function StyleSheet(){
	return "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
}

function getUploadDir($dir){
	global $Translation;

	if($dir==""){
		$dir=$Translation['ImageFolder'];
	}

	if(substr($dir, -1)!="/"){
		$dir.="/";
	}

	return $dir;
}

function PrepareUploadedFile($FieldName, $MaxSize, $FileTypes='jpg|jpeg|gif|png', $NoRename=false, $dir=""){
	global $HTTP_POST_FILES, $Translation;
	$f = $HTTP_POST_FILES[$FieldName];

	$dir=getUploadDir($dir);

	if($f['error'] != 4 && $f['name']!=''){
		if($f['size']>$MaxSize || $f['error']){
			echo StyleSheet()."<div class=Error>".str_replace("<MaxSize>", intval($MaxSize/1024), $Translation['file too large']).". <a href=".$_SERVER['HTTP_REFERER'].">".$Translation["< back"]."</a>.</div>";
			exit;
		}
		if(!eregi('\.('.$FileTypes.')$', $f['name'], $ft)){
			echo StyleSheet()."<div class=Error>".str_replace("<FileTypes>", str_replace('|', ', ', $FileTypes), $Translation['invalid file type']).". <a href=".$_SERVER['HTTP_REFERER'].">".$Translation["< back"]."</a>.</div>";
			exit;
		}

		if($NoRename){
			$n  = str_replace(' ', '_', $f['name']);
		}else{
			$n  = microtime();
			$n  = str_replace(' ', '_', $n);
			$n  = str_replace('0.', '', $n);
			$n .= $ft[0];
		}

		if(!file_exists($dir)){
			@mkdir($dir, 0777);
		}

		if(!@move_uploaded_file($f['tmp_name'], $dir . $n)){
			echo StyleSheet()."<div class=Error>Error: Couldn't save the uploaded file. Try chmoding the upload folder '".$dir."' to 777. <a href=".$_SERVER['HTTP_REFERER'].">".$Translation["< back"]."</a>.</div>";
			exit;
		}else{
			@chmod($dir.$n, 0666);
			return $n;
		}
	}
	return "";
}
?>