<?php
// This script and data application were generated by AppGini 4.2 on 1/19/2009 at 12:44:19 PM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/defaultLang.php");
	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/advertising_dml.php");

	// SQL query used in the filters page and the CSV file
	$filtersCSVQuery="select advertising.id as 'ID', advertising.contact_id as 'Contact id', advertising.contact_name as 'Contact name', advertising.advertising_radiotext as 'Text to annouce on the radio' from advertising ";
	// SQL query used in the table view
	$tableViewQuery="select advertising.id as 'ID', advertising.contact_id as 'Contact id', advertising.contact_name as 'Contact name', advertising.advertising_radiotext as 'Text to annouce on the radio' from advertising ";

	// mm: can the current member access this page?
	$perm=getTablePermissions('advertising');
	if(!$perm[0]){
		echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		exit;
	}

	$x = new DataList;
	$x->TableName = "advertising";
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "advertising_view.php";
	$x->RedirectAfterInsert = "advertising_view.php?SelectedID=#ID#";
	$x->TableTitle = "Advertising";
	$x->PrimaryKey = "advertising.id";

	$x->ColWidth   = array(150, 150, 150);
	$x->ColCaption = array("Contact id", "Contact name", "Text to annouce on the radio");
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'advertising_templateTV.html';
	$x->SelectedTemplate = 'advertising_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != ""){
		// Query used in filters page and CSV output
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where advertising.id=membership_userrecords.pkValue and membership_userrecords.tableName='advertising' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where advertising.id=membership_userrecords.pkValue and membership_userrecords.tableName='advertising' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $filtersCSVQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from advertising";
		}
	}else{
		// Query used in table view
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $tableViewQuery.", membership_userrecords  where advertising.id=membership_userrecords.pkValue and membership_userrecords.tableName='advertising' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $tableViewQuery.", membership_userrecords  where advertising.id=membership_userrecords.pkValue and membership_userrecords.tableName='advertising' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $tableViewQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from advertising";
		}
	}

	// handle date sorting correctly
	// end of date sorting handler


	$x->Render();

	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>