<?php

// Data functions for table advertising

// This script and data application were generated by AppGini 4.2 on 1/19/2009 at 12:44:19 PM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert(){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;

	if($HTTP_GET_VARS['insert_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('advertising');
	if(!$arrPerm[1]){
		return 0;
	}

	$contact_id = makeSafe($HTTP_POST_VARS["contact_id"]);
	$contact_name = makeSafe($HTTP_POST_VARS["contact_name"]);
	$advertising_radiotext = makeSafe($HTTP_POST_VARS["advertising_radiotext"]);

	sql("insert into advertising (contact_id, contact_name, advertising_radiotext) values (" . (($contact_id != "") ? "'$contact_id'" : "NULL") . ", " . (($contact_name != "") ? "'$contact_name'" : "NULL") . ", " . (($advertising_radiotext != "") ? "'$advertising_radiotext'" : "NULL") . ")");
	// mm: save ownership data
	$recID=mysql_insert_id();
	sql("insert into membership_userrecords set tableName='advertising', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'");

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	// mm: can member delete record?
	$arrPerm=getTablePermissions('advertising');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return FALSE;
	}

	// child table: donations
	$res = sql("select id from advertising where id='".makeSafe($selected_id)."'");
	$id = mysql_fetch_row($res);
	$rires = sql("select count(1) from donations where advertising_radiotext='".addslashes($id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='advertising_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='advertising_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}


	sql("delete from advertising where id='".makeSafe($selected_id)."'");

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
}

function update($selected_id){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;

	if($HTTP_GET_VARS['update_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('advertising');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return;
	}

	if(get_magic_quotes_gpc()){
		$contact_id = $HTTP_POST_VARS["contact_id"];
		$contact_name = $HTTP_POST_VARS["contact_name"];
		$advertising_radiotext = $HTTP_POST_VARS["advertising_radiotext"];
	}else{
		$contact_id = addslashes($HTTP_POST_VARS["contact_id"]);
		$contact_name = addslashes($HTTP_POST_VARS["contact_name"]);
		$advertising_radiotext = addslashes($HTTP_POST_VARS["advertising_radiotext"]);
	}

	sql("update advertising set " . "contact_id=" . (($contact_id != "") ? "'$contact_id'" : "NULL") . ", " . "contact_name=" . (($contact_name != "") ? "'$contact_name'" : "NULL") . ", " . "advertising_radiotext=" . (($advertising_radiotext != "") ? "'$advertising_radiotext'" : "NULL") . " where id='".makeSafe($selected_id)."'");

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");

}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;


	// mm: get table permissions
	$arrPerm=getTablePermissions('advertising');
	if(!$arrPerm[1] && $selected_id==""){ return ""; }

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='advertising' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		$res = sql("select * from advertising where id='".makeSafe($selected_id)."'");
		$row = mysql_fetch_array($res);
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	$templateCode=@implode('', @file('./advertising_templateDV.html'));

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

			// set records to read only if user can't insert new records
			if(!$arrPerm[1]){
				$jsReadOnly.="\n\n\tif(document.getElementsByName('id').length){ document.getElementsByName('id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_id').length){ document.getElementsByName('contact_id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_name').length){ document.getElementsByName('contact_name')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('advertising_radiotext').length){ document.getElementsByName('advertising_radiotext')[0].readOnly=true; }\n";

				$noUploads=true;
			}
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? "<input type=image src=cancel.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>" : ''), $templateCode);
	}

	// process combos

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(advertising_radiotext)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_id)%%>', htmlspecialchars($row['contact_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name)%%>', htmlspecialchars($row['contact_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(advertising_radiotext)%%>', htmlspecialchars($row['advertising_radiotext'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(advertising_radiotext)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);
	// hide links to inaccessible tables
	$templateCode.="\n\n<script>\n";
	$arrTables=getTableList();
	foreach($arrTables as $name=>$caption){
		$templateCode.="\tif(document.getElementById('".$name."_link')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_link').style.visibility='visible';\n";
		$templateCode.="\t}\n";
		$templateCode.="\tif(document.getElementById('".$name."_plink')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_plink').style.visibility='visible';\n";
		$templateCode.="\t}\n";
	}

	$templateCode.=$jsReadOnly;

	$templateCode.="\n</script>\n";


	// ajaxed auto-fill fields
	$templateCode.="<script src=\"prototype.js\"></script>";
	$templateCode.="<script>";
	$templateCode.="window.onload=function(){";


	$templateCode.="}";
	$templateCode.="</script>";

	return $templateCode;
}
?>