<?php

// Data functions for table donations

// This script and data application were generated by AppGini 4.2 on 1/19/2009 at 1:01:05 PM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert(){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;

	if($HTTP_GET_VARS['insert_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('donations');
	if(!$arrPerm[1]){
		return 0;
	}

	$donation_soldfor = makeSafe($HTTP_POST_VARS["donation_soldfor"]);
	$donation_year = makeSafe($HTTP_POST_VARS["donation_year"]);
	$contact_id = makeSafe($HTTP_POST_VARS["contact_id"]);
	$contact_name_ignore = makeSafe($HTTP_POST_VARS["contact_name_ignore"]);
	$stockitem_id = makeSafe($HTTP_POST_VARS["stockitem_id"]);
	$donation_item = makeSafe($HTTP_POST_VARS["donation_item"]);
	$donation_radiotext_lookup = makeSafe($HTTP_POST_VARS["donation_radiotext_lookup"]);
	$donation_radiotext = makeSafe($HTTP_POST_VARS["donation_radiotext"]);
	$donation_msrp = makeSafe($HTTP_POST_VARS["donation_msrp"]);
	$donation_url = makeSafe($HTTP_POST_VARS["donation_url"]);
	$donation_image = PrepareUploadedFile('donation_image', 2000000,'jpg|jpeg|gif|png', false, "");
	if($donation_year== ""){
		echo StyleSheet() . "\n\n<div class=Error>" . $Translation["error:"] . " 'Auction Year': " . $Translation['field not null'] . "</div>";
		exit;
	}

	sql("insert into donations (donation_year, contact_id, stockitem_id, donation_item, donation_radiotext_lookup, donation_radiotext, donation_msrp, donation_image, donation_url) values (" . (($donation_year != "") ? "'$donation_year'" : "NULL") . ", " . (($contact_id != "") ? "'$contact_id'" : "NULL") . ", " . (($stockitem_id != "") ? "'$stockitem_id'" : "NULL") . ", " . (($donation_item != "") ? "'$donation_item'" : "NULL") . ", " . (($donation_radiotext_lookup != "") ? "'$donation_radiotext_lookup'" : "NULL") . ", " . (($donation_radiotext != "") ? "'$donation_radiotext'" : "NULL") . ", " . (($donation_msrp != "") ? "'$donation_msrp'" : "NULL") . ", " . (($donation_image != "") ? "'$donation_image'" : "NULL") . ", " . (($donation_url != "") ? "'$donation_url'" : "NULL") . ")");
	// mm: save ownership data
	$recID=mysql_insert_id();
	$res = sql("select contact_name from contacts where id='".makeSafe($contact_id)."' limit 1");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			sql("update donations set contact_name_ignore='$row[0]' where id='".makeSafe($recID)."'");
		}
	}
	
	sql("insert into membership_userrecords set tableName='donations', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'");

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	// mm: can member delete record?
	$arrPerm=getTablePermissions('donations');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return FALSE;
	}

	// child table: donations
	$res = sql("select id from donations where id='".makeSafe($selected_id)."'");
	$id = mysql_fetch_row($res);
	$rires = sql("select count(1) from donations where donation_radiotext_lookup='".addslashes($id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "donations", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='donations_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='donations_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}


	// delete file stored in the 'donation_image' field
	$res = sql("select donation_image from donations where id='".makeSafe($selected_id)."'");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir("").$row[0]);
		}
	}

	sql("delete from donations where id='".makeSafe($selected_id)."'");

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
}

function update($selected_id){
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;

	if($HTTP_GET_VARS['update_x']){$HTTP_POST_VARS=$HTTP_GET_VARS;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('donations');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return;
	}

	if(get_magic_quotes_gpc()){
		$donation_soldfor = $HTTP_POST_VARS["donation_soldfor"];
		$donation_year = $HTTP_POST_VARS["donation_year"];
		$contact_id = $HTTP_POST_VARS["contact_id"];
		$contact_name_ignore = $HTTP_POST_VARS["contact_name_ignore"];
		$stockitem_id = $HTTP_POST_VARS["stockitem_id"];
		$donation_item = $HTTP_POST_VARS["donation_item"];
		$donation_radiotext_lookup = $HTTP_POST_VARS["donation_radiotext_lookup"];
		$donation_radiotext = $HTTP_POST_VARS["donation_radiotext"];
		$donation_msrp = $HTTP_POST_VARS["donation_msrp"];
		$donation_url = $HTTP_POST_VARS["donation_url"];
	}else{
		$donation_soldfor = addslashes($HTTP_POST_VARS["donation_soldfor"]);
		$donation_year = addslashes($HTTP_POST_VARS["donation_year"]);
		$contact_id = addslashes($HTTP_POST_VARS["contact_id"]);
		$contact_name_ignore = addslashes($HTTP_POST_VARS["contact_name_ignore"]);
		$stockitem_id = addslashes($HTTP_POST_VARS["stockitem_id"]);
		$donation_item = addslashes($HTTP_POST_VARS["donation_item"]);
		$donation_radiotext_lookup = addslashes($HTTP_POST_VARS["donation_radiotext_lookup"]);
		$donation_radiotext = addslashes($HTTP_POST_VARS["donation_radiotext"]);
		$donation_msrp = addslashes($HTTP_POST_VARS["donation_msrp"]);
		$donation_url = addslashes($HTTP_POST_VARS["donation_url"]);
	}

	if($HTTP_POST_VARS['donation_image_remove'] == 1){
		$donation_image = '';
		// delete file from server
		$res = sql("select donation_image from donations where id='".makeSafe($selected_id)."'");
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir("").$row[0]);
			}
		}
	}else{
		$donation_image = PrepareUploadedFile('donation_image', 2000000, 'jpg|jpeg|gif|png', false, "");
		// delete file from server
		if($donation_image != ''){
			$res = sql("select donation_image from donations where id='".makeSafe($selected_id)."'");
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir("").$row[0]);
				}
			}
		}
	}
	sql("update donations set " . "donation_year=" . (($donation_year != "") ? "'$donation_year'" : "NULL") . ", " . "contact_id=" . (($contact_id != "") ? "'$contact_id'" : "NULL") . ", " . "stockitem_id=" . (($stockitem_id != "") ? "'$stockitem_id'" : "NULL") . ", " . "donation_item=" . (($donation_item != "") ? "'$donation_item'" : "NULL") . ", " . "donation_radiotext_lookup=" . (($donation_radiotext_lookup != "") ? "'$donation_radiotext_lookup'" : "NULL") . ", " . "donation_radiotext=" . (($donation_radiotext != "") ? "'$donation_radiotext'" : "NULL") . ", " . "donation_msrp=" . (($donation_msrp != "") ? "'$donation_msrp'" : "NULL") . ", " . ($donation_image!="" ? "donation_image='$donation_image'" : ($HTTP_POST_VARS['donation_image_remove'] != 1 ? "donation_image=donation_image" : "donation_image=NULL")) . ", " . "donation_url=" . (($donation_url != "") ? "'$donation_url'" : "NULL") . " where id='".makeSafe($selected_id)."'");

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='donations' and pkValue='".makeSafe($selected_id)."'");

}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;


	// mm: get table permissions
	$arrPerm=getTablePermissions('donations');
	if(!$arrPerm[1] && $selected_id==""){ return ""; }
	// combobox: contact_id
	$combo_contact_id = new DataCombo;
	$combo_contact_id->Query = "select id, concat(contact_name, '') from contacts order by 2";
	$combo_contact_id->SelectName = "contact_id";
	// combobox: stockitem_id
	$combo_stockitem_id = new DataCombo;
	$combo_stockitem_id->Query = "select id, concat(stockitem_item, '') from stockitems order by 2";
	$combo_stockitem_id->SelectName = "stockitem_id";
	// combobox: donation_radiotext_lookup
	$combo_donation_radiotext_lookup = new DataCombo;
	$combo_donation_radiotext_lookup->Query = "select id, concat(contact_name_ignore, '::', donation_radiotext) from donations order by 2";
	$combo_donation_radiotext_lookup->SelectName = "donation_radiotext_lookup";

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select memberID from membership_userrecords where tableName='donations' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		$res = sql("select * from donations where id='".makeSafe($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_contact_id->SelectedData = $row["contact_id"];
		$combo_stockitem_id->SelectedData = $row["stockitem_id"];
		$combo_donation_radiotext_lookup->SelectedData = $row["donation_radiotext_lookup"];
	}else{
		$combo_contact_id->SelectedData = ( $_REQUEST['FilterField'][1]=='donations.contact_id' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_stockitem_id->SelectedData = ( $_REQUEST['FilterField'][1]=='donations.stockitem_id' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_donation_radiotext_lookup->SelectedData = ( $_REQUEST['FilterField'][1]=='donations.donation_radiotext_lookup' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_contact_id->Render();
	$combo_stockitem_id->Render();
	$combo_donation_radiotext_lookup->Render();

	// code for template based detail view forms

	// open the detail view template
	$templateCode=@implode('', @file('./donations_templateDV.html'));

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

			// set records to read only if user can't insert new records
			if(!$arrPerm[1]){
				$jsReadOnly.="\n\n\tif(document.getElementsByName('id').length){ document.getElementsByName('id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_soldfor').length){ document.getElementsByName('donation_soldfor')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_year').length){ document.getElementsByName('donation_year')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_id').length){ var contact_id=document.getElementsByName('contact_id')[0]; contact_id.disabled=true; contact_id.style.backgroundColor='white'; contact_id.style.color='black'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact_name_ignore').length){ document.getElementsByName('contact_name_ignore')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('stockitem_id').length){ var stockitem_id=document.getElementsByName('stockitem_id')[0]; stockitem_id.disabled=true; stockitem_id.style.backgroundColor='white'; stockitem_id.style.color='black'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_item').length){ document.getElementsByName('donation_item')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_radiotext_lookup').length){ var donation_radiotext_lookup=document.getElementsByName('donation_radiotext_lookup')[0]; donation_radiotext_lookup.disabled=true; donation_radiotext_lookup.style.backgroundColor='white'; donation_radiotext_lookup.style.color='black'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_radiotext').length){ document.getElementsByName('donation_radiotext')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_msrp').length){ document.getElementsByName('donation_msrp')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_image').length){ document.getElementsByName('donation_image')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('donation_url').length){ document.getElementsByName('donation_url')[0].readOnly=true; }\n";

				$noUploads=true;
			}
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? "<input type=image src=cancel.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>" : ''), $templateCode);
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(contact_id)%%>', $combo_contact_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(contact_id)%%>', $combo_contact_id->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(stockitem_id)%%>', $combo_stockitem_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(stockitem_id)%%>', $combo_stockitem_id->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(donation_radiotext_lookup)%%>', $combo_donation_radiotext_lookup->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(donation_radiotext_lookup)%%>', $combo_donation_radiotext_lookup->MatchText, $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(contact_id)%%>', ($combo_contact_id->SelectedData ? "<span id=contacts_plink style=\"visibility: hidden;\"><a href=contacts_view.php?SelectedID=".$combo_contact_id->SelectedData."><img border=0 src=lookup.gif></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(stockitem_id)%%>', ($combo_stockitem_id->SelectedData ? "<span id=stockitems_plink style=\"visibility: hidden;\"><a href=stockitems_view.php?SelectedID=".$combo_stockitem_id->SelectedData."><img border=0 src=lookup.gif></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(donation_radiotext_lookup)%%>', ($combo_donation_radiotext_lookup->SelectedData ? "<span id=donations_plink style=\"visibility: hidden;\"><a href=donations_view.php?SelectedID=".$combo_donation_radiotext_lookup->SelectedData."><img border=0 src=lookup.gif></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_soldfor)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_year)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact_name_ignore)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(stockitem_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_item)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_radiotext_lookup)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_radiotext)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_msrp)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(donation_image)%%>', ($noUploads ? '' : '<br><input type=hidden name=MAX_FILE_SIZE value=2000000>'.$Translation['upload image'].' <input type=file name="donation_image" class=TextBox>'), $templateCode);
	if($AllowUpdate && $row['donation_image']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(donation_image)%%>', '<br><input type=checkbox name="donation_image_remove" value="1"> <b class=Error>'.$Translation['remove image'].'</b>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(donation_image)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(donation_url)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_soldfor)%%>', htmlspecialchars($row['donation_soldfor'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_year)%%>', htmlspecialchars($row['donation_year'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_id)%%>', htmlspecialchars($row['contact_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name_ignore)%%>', htmlspecialchars($row['contact_name_ignore'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(stockitem_id)%%>', htmlspecialchars($row['stockitem_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_item)%%>', htmlspecialchars($row['donation_item'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_radiotext_lookup)%%>', htmlspecialchars($row['donation_radiotext_lookup'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_radiotext)%%>', htmlspecialchars($row['donation_radiotext'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_msrp)%%>', htmlspecialchars($row['donation_msrp'], ENT_QUOTES), $templateCode);
		$row['donation_image']=($row['donation_image']!=''?$row['donation_image']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(donation_image)%%>', htmlspecialchars($row['donation_image'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_url)%%>', htmlspecialchars($row['donation_url'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_soldfor)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_year)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact_name_ignore)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(stockitem_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_item)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_radiotext_lookup)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_radiotext)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_msrp)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_image)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(donation_url)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);
	// hide links to inaccessible tables
	$templateCode.="\n\n<script>\n";
	$arrTables=getTableList();
	foreach($arrTables as $name=>$caption){
		$templateCode.="\tif(document.getElementById('".$name."_link')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_link').style.visibility='visible';\n";
		$templateCode.="\t}\n";
		$templateCode.="\tif(document.getElementById('".$name."_plink')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_plink').style.visibility='visible';\n";
		$templateCode.="\t}\n";
	}

	$templateCode.=$jsReadOnly;

	$templateCode.="\n</script>\n";


	// ajaxed auto-fill fields
	$templateCode.="<script src=\"prototype.js\"></script>";
	$templateCode.="<script>";
	$templateCode.="window.onload=function(){";


	$templateCode.="}";
	$templateCode.="</script>";

	return $templateCode;
}
?>