<?php
// This script and data application were generated by AppGini 4.2 on 1/19/2009 at 1:01:05 PM
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/defaultLang.php");
	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/donations_dml.php");

	// SQL query used in the filters page and the CSV file
	$filtersCSVQuery="select donations.id as 'ID', donations.donation_soldfor as 'Donation Sold For', donations.donation_year as 'Auction Year', contacts4.contact_name as 'Donor', donations.contact_name_ignore as 'Contact name ignore', stockitems6.stockitem_item as 'Stock Item', donations.donation_item as 'Item', donations8.contact_name_ignore as 'Select text to annouce on the radio regarding this item', donations.donation_radiotext as 'Type text to annouce on the radio regarding this item', donations.donation_msrp as 'MSRP', donations.donation_image as 'Image to link to on the web', donations.donation_url as 'URL to link to on the web' from donations LEFT JOIN contacts as contacts4 ON donations.contact_id=contacts4.id LEFT JOIN stockitems as stockitems6 ON donations.stockitem_id=stockitems6.id LEFT JOIN donations as donations8 ON donations.donation_radiotext_lookup=donations8.id ";
	// SQL query used in the table view
	$tableViewQuery="select donations.id as 'ID', donations.donation_soldfor as 'Donation Sold For', donations.donation_year as 'Auction Year', if(CHAR_LENGTH(contacts4.contact_name)>100, concat(left(contacts4.contact_name,100),' ...'), contacts4.contact_name) as 'Donor', donations.contact_name_ignore as 'Contact name ignore', concat(stockitems6.stockitem_item, '') as 'Stock Item', if(CHAR_LENGTH(donations.donation_item)>100, concat(left(donations.donation_item,100),' ...'), donations.donation_item) as 'Item', concat(donations8.contact_name_ignore, '::', donations8.donation_radiotext) as 'Select text to annouce on the radio regarding this item', if(CHAR_LENGTH(donations.donation_radiotext)>120, concat(left(donations.donation_radiotext,120),' ...'), donations.donation_radiotext) as 'Type text to annouce on the radio regarding this item', donations.donation_msrp as 'MSRP', if(length(donations.donation_image), concat('<a href=" . getUploadDir("") . "',donations.donation_image,' target=_nWindow>',donations.donation_image,'</a>'), '') as 'Image to link to on the web', donations.donation_url as 'URL to link to on the web' from donations LEFT JOIN contacts as contacts4 ON donations.contact_id=contacts4.id LEFT JOIN stockitems as stockitems6 ON donations.stockitem_id=stockitems6.id LEFT JOIN donations as donations8 ON donations.donation_radiotext_lookup=donations8.id ";

	// mm: can the current member access this page?
	$perm=getTablePermissions('donations');
	if(!$perm[0]){
		echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		exit;
	}

	$x = new DataList;
	$x->TableName = "donations";
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "donations_view.php";
	$x->RedirectAfterInsert = "donations_view.php?LastID=#ID#";
	$x->TableTitle = "Donations";
	$x->PrimaryKey = "donations.id";
	$x->DefaultSortField = "1";
	$x->DefaultSortDirection = "asc";

	$x->ColWidth   = array(150, 150, 150, 250, 150, 150, 150);
	$x->ColCaption = array("ID", "Donor", "Stock Item", "Item", "Select text to annouce on the radio regarding this item", "Type text to annouce on the radio regarding this item", "MSRP");
	$x->ColNumber  = array(1, 4, 6, 7, 8, 9, 10);

	$x->Template = 'donations_templateTV.html';
	$x->SelectedTemplate = 'donations_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != ""){
		// Query used in filters page and CSV output
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where donations.id=membership_userrecords.pkValue and membership_userrecords.tableName='donations' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $filtersCSVQuery.", membership_userrecords  where donations.id=membership_userrecords.pkValue and membership_userrecords.tableName='donations' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $filtersCSVQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from donations";
		}
	}else{
		// Query used in table view
		// mm: build the query based on current member's permissions
		if($perm[2]==1){ // view owner only
			$x->Query = $tableViewQuery.", membership_userrecords  where donations.id=membership_userrecords.pkValue and membership_userrecords.tableName='donations' and membership_userrecords.memberID='".getLoggedMemberID()."'";
		}elseif($perm[2]==2){ // view group only
			$x->Query = $tableViewQuery.", membership_userrecords  where donations.id=membership_userrecords.pkValue and membership_userrecords.tableName='donations' and membership_userrecords.groupID='".getLoggedGroupID()."'";
		}elseif($perm[2]==3){ // view all
			$x->Query = $tableViewQuery."";
		}elseif($perm[2]==0){ // view none
			$x->Query = "select 'Not enough permissions' from donations";
		}
	}

	// handle date sorting correctly
	// end of date sorting handler


	$x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		$sumQuery="select sum(donations.donation_msrp) ".strstr($x->Query, 'from donations');
		if(strpos(strtolower($sumQuery), ' order by ')){
			$sumQuery=str_replace(' order by ', "/*", $sumQuery)."*/";
		}
		$sumStyle="color: green; background-color:".$x->HighlightColor.";";
		$res=sql($sumQuery);
		if($row=mysql_fetch_row($res)){
			$sumRow ="<tr>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\"><b>&sum;</b></td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableBodyNumeric\" style=\"$sumStyle\">&nbsp;$row[0]</td>";
			$sumRow.="</tr>";
			
			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>