# show create function X;
# show function status where db='rra_master';
# select name,param_list,returns,body from mysql.proc where db='rra_master'\G
# select * from information_schema.routines where ROUTINE_SCHEMA='rra_master'\G
# select TABLE_NAME,VIEW_DEFINITION from information_schema.views where table_schema='rra_master'\G
select column_name,data_type from information_schema.columns where table_schema='rra_master' and table_name='items_vw' order by table_name limit 100;
select table_name,table_type,table_rows from information_schema.tables where table_schema='rra_master' order by table_type, table_name;

show grants for washingtonrotary@'%';
grant select on mysql.proc to washingtonrotary@'%';


# echo 'select name,param_list,returns,body from proc where db="rra_master"' | /usr/bin/mysql -u root -psecret mysql | perl -pi -e 'chomp;s/\\n| +/ /g; @_=split/\t/;$_="CREATE FUNCTION $_[0] ($_[1]) RETURNS $_[2] $_[3]//\n"'
CREATE FUNCTION auction () RETURNS varchar(255) CHARSET utf8 BEGIN  DECLARE ynl VARCHAR(255);  SELECT CONCAT_WS('::', year,night,live) INTO ynl FROM auctions WHERE now() BETWEEN start AND end ORDER BY live DESC LIMIT 1;  RETURN ynl; END//
CREATE FUNCTION auction_live () RETURNS smallint(1) BEGIN  DECLARE l SMALLINT(1);  SELECT live INTO l FROM auctions WHERE now() BETWEEN start AND end ORDER BY live DESC LIMIT 1;  RETURN l; END//
CREATE FUNCTION auction_night () RETURNS enum('1','2','3','4') CHARSET utf8 BEGIN  DECLARE n ENUM('1','2','3','4');  SELECT night INTO n FROM auctions WHERE now() BETWEEN start AND end ORDER BY live DESC LIMIT 1;  RETURN n; END//
CREATE FUNCTION auction_year () RETURNS year(4) BEGIN DECLARE y YEAR; SELECT year INTO y FROM auctions WHERE now() BETWEEN start AND end ORDER BY live DESC LIMIT 1; RETURN y; END//
CREATE FUNCTION date2night (d datetime) RETURNS enum('1','2','3','4') CHARSET utf8 BEGIN  DECLARE n enum('1','2','3','4');  SELECT night into n from auctions where d between start and end order by live desc limit 1;  RETURN n; END//
CREATE FUNCTION GetStatus (id int(11) unsigned) RETURNS varchar(20) CHARSET utf8 BEGIN  DECLARE s VARCHAR(20);  DECLARE my_scheduled datetime;  DECLARE my_started datetime;  DECLARE my_sold datetime;  DECLARE my_cleared datetime;  DECLARE my_auctioneer enum('a', 'b');  SELECT scheduled, started, sold, cleared, auctioneer INTO my_scheduled, my_started, my_sold, my_cleared, my_auctioneer FROM items WHERE item_id=id;  IF (my_scheduled IS NOT NULL AND my_started IS NULL AND my_sold IS NULL AND my_cleared IS NULL AND my_auctioneer IS NULL) THEN SET s = 'Scheduled';  ELSEIF (my_scheduled IS NOT NULL AND my_started IS NULL AND my_sold IS NULL AND my_cleared IS NULL AND my_auctioneer IS NULL) THEN SET s = 'Ready';  ELSEIF (my_scheduled IS NOT NULL AND my_started IS NULL AND my_sold IS NULL AND my_cleared IS NULL AND my_auctioneer IS NOT NULL) THEN SET s = 'OnDeck';  ELSEIF (my_scheduled IS NOT NULL AND my_started IS NOT NULL AND my_sold IS NULL AND my_cleared IS NULL AND my_auctioneer IS NOT NULL) THEN SET s = 'Bidding';  ELSEIF (my_scheduled IS NOT NULL AND my_started IS NOT NULL AND my_sold IS NOT NULL AND my_cleared IS NULL AND my_auctioneer IS NOT NULL) THEN SET s = 'Sold';  ELSEIF (my_scheduled IS NOT NULL AND my_started IS NOT NULL AND my_sold IS NOT NULL AND my_cleared IS NOT NULL AND my_auctioneer IS NOT NULL) THEN SET s = 'Complete';  ELSE SET s = null;  END IF;  RETURN s; END//
CREATE FUNCTION ItemCount (id int(11) unsigned) RETURNS int(11) unsigned begin declare i int(11) unsigned; select count(0) into i from items where year = auction_year() and donor_id=id; return i; end//
CREATE FUNCTION queue (s varchar(20), a enum('a','b')) RETURNS int(11) BEGIN  DECLARE c INT;  SELECT count(*) AS c INTO c FROM items_vw WHERE status=s AND auctioneer=a;  RETURN c; END//
CREATE FUNCTION StartBid (value int(11) unsigned) RETURNS int(11) unsigned return if(value < 100, 5, if(value < 250, 30, 50))//

# echo 'show create view adcount_cyn\G show create view ads_cy\G show create view auctions_cyn\G show create view bidders_cy\G show create view donors_items_vw\G show create view donors_vw\G show create view highbids_vw\G show create view items_cyn\G show create view items_vw\G show create view stockbellringers_cy\G show create view stockitems_cy\G show create view winners_vw\G' | mysql -u washingtonrotary -pharris rra_master | grep 'Create View:' | perl -pi -e 's/^\s+Create View:\s+//; s/ALGORITHM=.*?DEFINER\s+//; s/$/;/' 
CREATE VIEW `adcount_cyn` AS select `adcount`.`ad_id` AS `ad_id`,`adcount`.`year` AS `year`,`adcount`.`night` AS `night`,`adcount`.`display` AS `display`,`adcount`.`click` AS `click` from `adcount` where ((`adcount`.`year` = `auction_year`()) and (`adcount`.`night` = `auction_night`()));
CREATE VIEW `ads_cy` AS select `ads`.`ad_id` AS `ad_id`,`ads`.`year` AS `year`,`ads`.`donor_id` AS `donor_id`,`ads`.`url` AS `url` from `ads` where (`ads`.`year` = `auction_year`());
CREATE VIEW `auctions_cyn` AS select `auction_year`() AS `year`,`auction_night`() AS `night`,`auction_live`() AS `live`;
CREATE VIEW `bidders_cy` AS select `bidders`.`bidder_id` AS `bidder_id`,`bidders`.`year` AS `year`,`bidders`.`phone` AS `phone`,`bidders`.`bidder` AS `bidder`,`bidders`.`address` AS `address`,`bidders`.`city` AS `city`,`bidders`.`state` AS `state`,`bidders`.`zip` AS `zip`,`bidders`.`email` AS `email` from `bidders` where (`bidders`.`year` = `auction_year`());
CREATE VIEW `donors_vw` AS select `donors`.`rotarian_id` AS `rotarian_id`,`donors`.`donor_id` AS `donor_id`,`donors`.`chamberid` AS `chamberid`,`donors`.`phone` AS `phone`,`donors`.`donor` AS `donor`,`donors`.`category` AS `category`,`donors`.`contact1` AS `contact1`,`donors`.`contact2` AS `contact2`,concat_ws('|',`donors`.`contact1`,`donors`.`contact2`) AS `contact`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`state` AS `state`,`donors`.`zip` AS `zip`,`donors`.`email` AS `email`,`donors`.`url` AS `url`,`donors`.`advertisement` AS `advertisement`,`donors`.`solicit` AS `solicit`,`donors`.`comments` AS `comments`,concat_ws(', ',`rotarians`.`lastname`,`rotarians`.`firstname`) AS `rotarian`,`ItemCount`(`donors`.`donor_id`) AS `items` from (`donors` left join `rotarians` on((`donors`.`rotarian_id` = `rotarians`.`rotarian_id`))) group by `donors`.`donor_id`;
CREATE VIEW `highbids_vw` AS select `bids`.`bid_id` AS `bid_id`,`bidders`.`bidder_id` AS `bidder_id`,`bidders`.`bidder` AS `bidder`,`bids`.`item_id` AS `item_id`,max(`bids`.`bid`) AS `highbid`,time_to_sec(timediff(now(),`bids`.`bidtime`)) AS `bidage`,`bids`.`bidtime` AS `bidtime` from (`bids` left join `bidders` on((`bids`.`bidder_id` = `bidders`.`bidder_id`))) group by `bids`.`item_id`;
CREATE VIEW `items_vw` AS select `items`.`item_id` AS `item_id`,`items`.`year` AS `year`,`donors`.`donor_id` AS `donor_id`,`donors`.`donor` AS `donor`,`donors`.`url` AS `donorurl`,`items`.`seq` AS `seq`,`items`.`number` AS `number`,`items`.`category` AS `category`,`items`.`item` AS `item`,`items`.`description` AS `description`,`items`.`url` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`GetStatus`(`items`.`item_id`) AS `status`,`items`.`notify` AS `notify`,`donors`.`advertisement` AS `advertisement`,if(isnull(`highbids_vw`.`bidder`),'-',`highbids_vw`.`bidder`) AS `bidder`,`highbids_vw`.`highbid` AS `highbid`,`StartBid`(`items`.`value`) AS `startbid`,if(isnull(`highbids_vw`.`highbid`),`StartBid`(`items`.`value`),if((`highbids_vw`.`highbid` < `items`.`value`),(`highbids_vw`.`highbid` + 5),(`highbids_vw`.`highbid` + 1))) AS `minbid`,`highbids_vw`.`bidtime` AS `bidtime`,`highbids_vw`.`bidage` AS `bidage`,if(isnull(`items`.`timer`),NULL,if((truncate((time_to_sec(timediff(now(),`items`.`timer`)) / 60),1) > 5),1,0)) AS `cansell`,if((`highbids_vw`.`highbid` >= `items`.`value`),1,NULL) AS `bellringer`,`date2night`(`items`.`scheduled`) AS `scheduled`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,if(isnull(`items`.`timer`),NULL,truncate((time_to_sec(timediff(now(),`items`.`timer`)) / 60),1)) AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from ((`items` left join `highbids_vw` on((`items`.`item_id` = `highbids_vw`.`item_id`))) left join `donors` on((`items`.`donor_id` = `donors`.`donor_id`))) order by `items`.`seq`;
CREATE VIEW `stockbellringers_cy` AS select `stockbellringers`.`stockbellringers_id` AS `stockbellringers_id`,`stockbellringers`.`year` AS `year`,`stockbellringers`.`name` AS `name` from `stockbellringers` where (`stockbellringers`.`year` = `auction_year`());
CREATE VIEW `stockitems_cy` AS select `stockitems`.`stockitem_id` AS `stockitem_id`,`stockitems`.`year` AS `year`,`stockitems`.`category` AS `category`,`stockitems`.`stockitem` AS `stockitem`,`stockitems`.`value` AS `value`,`stockitems`.`cost` AS `cost` from `stockitems` where (`stockitems`.`year` = `auction_year`());
CREATE VIEW `winners_vw` AS select `bids`.`item_id` AS `item_id`,`bidders`.`bidder` AS `bidder`,`bidders`.`phone` AS `phone`,max(`bids`.`bid`) AS `highbid`,`items`.`contacted` AS `contacted` from ((`bids` left join `bidders` on((`bids`.`bidder_id` = `bidders`.`bidder_id`))) left join `items` on((`bids`.`item_id` = `items`.`item_id`))) where (`items`.`sold` is not null) group by `bids`.`item_id`;
CREATE VIEW `donors_items_vw` AS select `items_vw`.`donor_id` AS `donor_id`,`items_vw`.`year` AS `year`,`date2night`(`items_vw`.`sold`) AS `sold`,`items_vw`.`number` AS `number`,`items_vw`.`item` AS `item`,`items_vw`.`value` AS `value`,`items_vw`.`highbid` AS `highbid`,if(`items_vw`.`bellringer`,'Yes','No') AS `bellringer` from `items_vw` order by `items_vw`.`year` desc,if(`items_vw`.`bellringer`,'Yes','No') desc,`items_vw`.`highbid` desc;
CREATE VIEW `items_cyn` AS select `items_vw`.`item_id` AS `item_id`,`items_vw`.`year` AS `year`,`items_vw`.`donor_id` AS `donor_id`,`items_vw`.`donor` AS `donor`,`items_vw`.`donorurl` AS `donorurl`,`items_vw`.`seq` AS `seq`,`items_vw`.`number` AS `number`,`items_vw`.`category` AS `category`,`items_vw`.`item` AS `item`,`items_vw`.`description` AS `description`,`items_vw`.`itemurl` AS `itemurl`,`items_vw`.`value` AS `value`,`items_vw`.`auctioneer` AS `auctioneer`,`items_vw`.`status` AS `status`,`items_vw`.`notify` AS `notify`,`items_vw`.`advertisement` AS `advertisement`,`items_vw`.`bidder` AS `bidder`,`items_vw`.`highbid` AS `highbid`,`items_vw`.`startbid` AS `startbid`,`items_vw`.`minbid` AS `minbid`,`items_vw`.`bidtime` AS `bidtime`,`items_vw`.`bidage` AS `bidage`,`items_vw`.`cansell` AS `cansell`,`items_vw`.`bellringer` AS `bellringer`,`items_vw`.`scheduled` AS `scheduled`,`items_vw`.`started` AS `started`,`items_vw`.`timer` AS `timer`,`items_vw`.`timerminutes` AS `timerminutes`,`items_vw`.`sold` AS `sold`,`items_vw`.`cleared` AS `cleared`,`items_vw`.`contacted` AS `contacted` from `items_vw` where ((`items_vw`.`year` = `auction_year`()) and (`items_vw`.`scheduled` = `auction_night`()));
