-- TABLE_NAME			VIEW_DEFINITION
-- 
drop view if exists performance_donors_current_vw; create view performance_donors_current_vw as select `donors`.`donor_id` AS `donor_id`,count(`items`.`item_id`) AS `items`,sum(if(isnull(`items`.`value`),0,`items`.`value`)) AS `value`,sum(if(isnull(`items`.`highbid`),0,`items`.`highbid`)) AS `sales` from (`donors_vw` `donors` left join `items_current_vw` `items` on((`donors`.`donor_id` = `items`.`donor_id`))) group by `donors`.`donor_id` with rollup;
drop view if exists performance_donors_last_vw; create view performance_donors_last_vw as select `donors`.`donor_id` AS `donor_id`,count(`items`.`item_id`) AS `items`,sum(if(isnull(`items`.`value`),0,`items`.`value`)) AS `value`,sum(if(isnull(`items`.`highbid`),0,`items`.`highbid`)) AS `sales` from (`donors_vw` `donors` left join `items_last_vw` `items` on((`donors`.`donor_id` = `items`.`donor_id`))) group by `donors`.`donor_id` with rollup;
drop view if exists performance_donors_vw; create view performance_donors_vw as select `donors`.`donor_id` AS `donor_id`,count(`items`.`item_id`) AS `items`,sum(if(isnull(`items`.`value`),0,`items`.`value`)) AS `value`,sum(if(isnull(`items`.`highbid`),0,`items`.`highbid`)) AS `sales` from (`donors_vw` `donors` left join `items_vw` `items` on((`donors`.`donor_id` = `items`.`donor_id`))) group by `donors`.`donor_id` with rollup;
drop view if exists performance_rotarians_current_vw; create view performance_rotarians_current_vw as select `donors`.`rotarian_id` AS `rotarian_id`,count(`performance`.`items`) AS `donors`,sum(`performance`.`items`) AS `items`,sum(`performance`.`value`) AS `value`,sum(`performance`.`sales`) AS `sales` from (`performance_donors_current_vw` `performance` join `donors` on((`performance`.`donor_id` = `donors`.`donor_id`))) group by `donors`.`rotarian_id` with rollup;
drop view if exists performance_rotarians_last_vw; create view performance_rotarians_last_vw as select `donors`.`rotarian_id` AS `rotarian_id`,count(`performance`.`items`) AS `donors`,sum(`performance`.`items`) AS `items`,sum(`performance`.`value`) AS `value`,sum(`performance`.`sales`) AS `sales` from (`performance_donors_last_vw` `performance` join `donors` on((`performance`.`donor_id` = `donors`.`donor_id`))) group by `donors`.`rotarian_id` with rollup;
drop view if exists performance_rotarians_vw; create view performance_rotarians_vw as select `donors`.`rotarian_id` AS `rotarian_id`,count(`performance`.`items`) AS `donors`,sum(`performance`.`items`) AS `items`,sum(`performance`.`value`) AS `value`,sum(`performance`.`sales`) AS `sales` from (`performance_donors_vw` `performance` join `donors` on((`performance`.`donor_id` = `donors`.`donor_id`))) group by `donors`.`rotarian_id` with rollup;
drop view if exists performance_night_current_vw; create view performance_night_current_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_current_vw auctions join items_current_vw on night>0 and sold between start and end group by auctions.year,auctions.night;
drop view if exists performance_night_last_vw; create view performance_night_last_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_current_vw auctions join items_last_vw on night>0 and sold between start and end group by auctions.year,auctions.night;
drop view if exists performance_night_vw; create view performance_night_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_vw auctions join items_vw on night>0 and sold between start and end group by auctions.year,auctions.night with rollup;
drop view if exists performance_auctions_current_vw; create view performance_auctions_current_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_current_vw auctions join items_current_vw on night>0 and sold between start and end group by auctions.year;
drop view if exists performance_auctions_last_vw; create view performance_auctions_last_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_current_vw auctions join items_last_vw on night>0 and sold between start and end group by auctions.year;
drop view if exists performance_auctions_vw; create view performance_auctions_vw as select auctions.year,auctions.night,count(item_id) items,sum(value) value,sum(highbid) sales from auctions_vw auctions join items_vw on night>0 and sold between start and end group by auctions.year with rollup;
-- 
drop view if exists costs_stockitems_current_vw; create view costs_stockitems_current_vw as select items.item,count(item_id) qty,sum(cost) cost,sum(stockitems.value) value,sum(items.highbid) sales from items_current_vw items join stockitems on items.stockitem_id=stockitems.stockitem_id group by items.item with rollup;
drop view if exists costs_stockitems_last_vw; create view costs_stockitems_last_vw as select items.item,count(item_id) qty,sum(cost) cost,sum(stockitems.value) value,sum(items.highbid) sales from items_last_vw items join stockitems on items.stockitem_id=stockitems.stockitem_id group by items.item with rollup;
drop view if exists costs_stockitems_vw; create view costs_stockitems_vw as select stockitems.stockitem_id,stockitems.stockitem,count(item_id) items,sum(cost) cost,sum(stockitems.value) value,sum(items.highbid) sales from items_vw items join stockitems on items.stockitem_id=stockitems.stockitem_id group by items.stockitem_id with rollup;
-- 
drop view if exists ac_ad_vw; create view ac_ad_vw as select `ads`.`ad` AS `ad`,concat_ws('|',concat_ws(':',`ads`.`ad`,`ads`.`ad_id`),`ads`.`url`) AS `ac` from `ads` join `auctions_current_vw` `year` on((`ads`.`year` = `year`.`year`)) group by `ads`.`ad` order by `ads`.`ad`;
drop view if exists ac_advertisement_vw; create view ac_advertisement_vw as select `donors`.`donor_id` AS `donor_id`,`donors`.`advertisement` AS `ac` from `donors` group by `donors`.`advertisement` order by `donors`.`advertisement`;
drop view if exists ac_advertiser_vw; create view ac_advertiser_vw as select `donors`.`donor_id` AS `advertiser_id`,`donors`.`donor` AS `advertiser`,concat_ws('|',concat_ws(':',`donors`.`donor`,`donors`.`donor_id`),`donors`.`url`) AS `ac` from `donors` group by `donors`.`donor_id` order by `donors`.`donor`;
drop view if exists ac_city_vw; create view ac_city_vw as select `donors`.`city` AS `city`,concat_ws('|',`donors`.`city`,`donors`.`state`,`donors`.`zip`) AS `ac` from `donors` group by `donors`.`city` order by `donors`.`city`;
drop view if exists ac_donor_vw; create view ac_donor_vw as select `donors`.`donor_id` AS `donor_id`,`donors`.`donor` AS `donor`,concat_ws('|',concat_ws(':',`donors`.`donor`,`donors`.`donor_id`),`donors`.`advertisement`) AS `ac` from `donors` group by `donors`.`donor_id` order by `donors`.`donor`;
drop view if exists ac_item_stockitem_vw; create view ac_item_stockitem_vw as select concat('(',`stockitems`.`value`,') ',`stockitems`.`stockitem`,':',`stockitems`.`stockitem_id`,'|',`stockitems`.`stockitem`,'|',`stockitems`.`value`) AS `ac` from `stockitems` join `auctions_current_vw` `year` on((`stockitems`.`year` = `year`.`year`)) group by `stockitems`.`stockitem` order by `stockitems`.`stockitem`;
drop view if exists ac_item_vw; create view ac_item_vw as select `items`.`item_id` AS `item_id`,`items`.`item` AS `item`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`number` AS `number`,concat_ws('|',`items`.`item`,`items`.`description`,`items`.`value`,`items`.`itemurl`,`items`.`itemcat`) AS `ac` from `items_recent_vw` `items` where ((`items`.`item` is not null) and (`items`.`donor` is not null) and (`items`.`item_id` is not null) and (`items`.`donor_id` is not null)) group by `items`.`item` order by `items`.`item`;
drop view if exists ac_pay_number_vw; create view ac_pay_number_vw as select concat('(',`items`.`number`,') ',`items`.`item`) AS `label`,`items`.`number` AS `value`,`items`.`number` AS `number`,`items`.`item` AS `item`,`items`.`highbidder` AS `highbidder`,`bidders`.`address` AS `address`,concat_ws(', ',`bidders`.`city`,`bidders`.`state`,`bidders`.`zip`) AS `csz` from (`items_current_vw` `items` left join `bidders` on((`items`.`highbidder_id` = `bidders`.`bidder_id`)));
drop view if exists ac_stockitem_vw; create view ac_stockitem_vw as select `stockitems`.`stockitem` AS `stockitem`,concat_ws('|',concat_ws(':',`stockitems`.`stockitem`,`stockitems`.`stockitem_id`),`stockitems`.`stockitem`,`stockitems`.`value`,`stockitems`.`category`) AS `ac` from `stockitems` join `auctions_current_vw` `year` on((`stockitems`.`year` = `year`.`year`)) group by `stockitems`.`stockitem` order by `stockitems`.`stockitem`;
-- 
drop view if exists adcount_today_vw; create view adcount_today_vw as select `adcount`.`ad_id` AS `ad_id`,`adcount`.`advertiser_id` AS `advertiser_id`,`adcount`.`scheduled` AS `scheduled`,`adcount`.`adurl` AS `adurl`,`adcount`.`processed` AS `processed`,`adcount`.`rotate` AS `rotate`,`adcount`.`display` AS `display`,`adcount`.`click` AS `click` from `adcount_vw` `adcount` where ((`adcount`.`processed` = cast(now() as date)) or isnull(`adcount`.`processed`));
drop view if exists adcount_vw; create view adcount_vw as select `ads`.`ad_id` AS `ad_id`,`ads`.`year` AS `year`,`ads`.`advertiser_id` AS `advertiser_id`,`ads`.`scheduled` AS `scheduled`,`ads`.`adurl` AS `adurl`,`adcount`.`processed` AS `processed`,`adcount`.`rotate` AS `rotate`,`adcount`.`display` AS `display`,`adcount`.`click` AS `click` from (`ads_vw` `ads` left join `adcount` on((`ads`.`ad_id` = `adcount`.`ad_id`)));
-- 
drop view if exists ads_today_vw; create view ads_today_vw as select `ads`.`ad_id` AS `ad_id`,`ads`.`scheduled` AS `scheduled`,`ads`.`advertiser_id` AS `advertiser_id`,`ads`.`advertiser` AS `advertiser`,`ads`.`ad` AS `ad`,`ads`.`adurl` AS `adurl` from `ads_vw` `ads` where ((`ads`.`scheduled` = cast(now() as date)) or isnull(`ads`.`scheduled`));
drop view if exists ads_vw; create view ads_vw as select `ads`.`ad_id` AS `ad_id`,`ads`.`year` AS `year`,`ads`.`scheduled` AS `scheduled`,`ads`.`advertiser_id` AS `advertiser_id`,`donors`.`donor` AS `advertiser`,`ads`.`ad` AS `ad`,`ads`.`url` AS `adurl` from (`ads` join `donors` on((`donors`.`donor_id` = `ads`.`advertiser_id`)));
-- 
drop view if exists auctions_current_vw; create view auctions_current_vw as select `auctions`.`year` AS `year`,`auctions`.`start` AS `start`,`auctions`.`end` AS `end`,`auctions`.`night` AS `night`,if((`auctions`.`night` > 0),1,0) AS `live` from `auctions_vw` `auctions` where (now() between `auctions`.`start` and `auctions`.`end`) order by if((`auctions`.`night` > 0),1,0) desc,`auctions`.`night` desc limit 1;
drop view if exists auctions_night1_vw_ss; create view auctions_night1_vw_ss as select `auctions`.`year` AS `year`,dayofyear(min(`auctions`.`start`)) AS `night1` from `auctions` where (timestampdiff(HOUR,`auctions`.`start`,`auctions`.`end`) < 24) group by `auctions`.`year`;
drop view if exists auctions_next_vw; create view auctions_next_vw as select `auctions`.`year` AS `year`,`auctions`.`night` AS `night`,date_format(`auctions`.`start`,'%a, %M %e, %Y') AS `date`,date_format(`auctions`.`start`,'%r') AS `time` from `auctions_vw` `auctions` where ((`auctions`.`night` > 0) and (`auctions`.`start` > now())) order by `auctions`.`start` limit 1;
drop view if exists auctions_vw; create view auctions_vw as select `auctions`.`year` AS `year`,`auctions`.`start` AS `start`,`auctions`.`end` AS `end`,if((timestampdiff(HOUR,`auctions`.`start`,`auctions`.`end`) < 24),((dayofyear(`auctions`.`start`) - `night1`.`night1`) + 1),0) AS `night` from (`auctions` join `auctions_night1_vw_ss` `night1` on((`auctions`.`year` = `night1`.`year`))) order by `auctions`.`year` desc,`auctions`.`start`;
-- 
drop view if exists bellcount_current_vw; create view bellcount_current_vw as select `bellcount`.`bidder_id` AS `bidder_id`,`bellcount`.`bellitem_id` AS `bellitem_id`,`bellcount`.`qty` AS `qty`,`bellcount`.`bellitem` AS `bellitem`,`bellcount`.`phone` AS `phone`,`bellcount`.`bidder` AS `bidder`,`bellcount`.`address` AS `address`,`bellcount`.`city` AS `city`,`bellcount`.`state` AS `state`,`bellcount`.`zip` AS `zip`,`bellcount`.`email` AS `email` from (`bellcount_vw` `bellcount` join `auctions_current_vw` `year` on((`bellcount`.`year` = `year`.`year`)));
drop view if exists bellcount_vw; create view bellcount_vw as select `bellcount`.`bidder_id` AS `bidder_id`,`bellitems`.`year` AS `year`,`bellcount`.`bellitem_id` AS `bellitem_id`,`bellcount`.`qty` AS `qty`,`bellitems`.`bellitem` AS `bellitem`,`bidders`.`phone` AS `phone`,`bidders`.`bidder` AS `bidder`,`bidders`.`address` AS `address`,`bidders`.`city` AS `city`,`bidders`.`state` AS `state`,`bidders`.`zip` AS `zip`,`bidders`.`email` AS `email` from ((`bellcount` left join `bellitems` on((`bellcount`.`bellitem_id` = `bellitems`.`bellitem_id`))) left join `bidders` on((`bellcount`.`bidder_id` = `bidders`.`bidder_id`)));
-- 
drop view if exists bellitems_current_vw; create view bellitems_current_vw as select `bellitems`.`bellitem_id` AS `bellitem_id`,`bellitems`.`bellitem` AS `bellitem` from (`bellitems_vw` `bellitems` join `auctions_current_vw` `year` on((`bellitems`.`year` = `year`.`year`)));
drop view if exists bellitems_vw; create view bellitems_vw as select `bellitems`.`bellitem_id` AS `bellitem_id`,`bellitems`.`year` AS `year`,`bellitems`.`bellitem` AS `bellitem` from `bellitems`;
-- 
drop view if exists bidders_current_vw; create view bidders_current_vw as select `bidders`.`bidder_id` AS `bidder_id`,`bidders`.`phone` AS `phone`,`bidders`.`bidder` AS `bidder`,`bidders`.`address` AS `address`,`bidders`.`city` AS `city`,`bidders`.`state` AS `state`,`bidders`.`zip` AS `zip`,`bidders`.`email` AS `email` from (`bidders_vw` `bidders` join `auctions_current_vw` `year` on((`bidders`.`year` = `year`.`year`)));
drop view if exists bidders_vw; create view bidders_vw as select `bidders`.`bidder_id` AS `bidder_id`,`bidders`.`year` AS `year`,`bidders`.`phone` AS `phone`,`bidders`.`bidder` AS `bidder`,`bidders`.`address` AS `address`,`bidders`.`city` AS `city`,`bidders`.`state` AS `state`,`bidders`.`zip` AS `zip`,`bidders`.`email` AS `email` from `bidders`;
-- 
drop view if exists bids_current_vw; create view bids_current_vw as select `bids`.`bid_id` AS `bid_id`,`bids`.`bidder_id` AS `bidder_id`,`bids`.`item_id` AS `item_id`,`bids`.`bid` AS `bid`,`bids`.`bidtime` AS `bidtime` from ((`bids_vw` `bids` join `items` on((`bids`.`item_id` = `items`.`item_id`))) join `auctions_current_vw` `year` on((`items`.`year` = `year`.`year`)));
drop view if exists bids_vw; create view bids_vw as select `bids`.`bid_id` AS `bid_id`,`bids`.`bidder_id` AS `bidder_id`,`bids`.`item_id` AS `item_id`,`bids`.`bid` AS `bid`,`bids`.`bidtime` AS `bidtime` from `bids`;
-- 
drop view if exists donors_nosolicit_vw; create view donors_nosolicit_vw as select `donors`.`rotarian_id` AS `rotarian_id`,`donors`.`donor_id` AS `donor_id`,`donors`.`chamberid` AS `chamberid`,`donors`.`phone` AS `phone`,`donors`.`donor` AS `donor`,`donors`.`category` AS `category`,`donors`.`contact1` AS `contact1`,`donors`.`contact2` AS `contact2`,concat_ws('|',`donors`.`contact1`,`donors`.`contact2`) AS `contact`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`state` AS `state`,`donors`.`zip` AS `zip`,`donors`.`email` AS `email`,`donors`.`url` AS `url`,`donors`.`advertisement` AS `advertisement`,`donors`.`solicit` AS `solicit`,`donors`.`comments` AS `comments`,concat_ws(', ',`rotarians`.`lastname`,`rotarians`.`firstname`) AS `rotarian` from (`donors` left join `rotarians` on((`donors`.`rotarian_id` = `rotarians`.`rotarian_id`))) where solicit=0 group by `donors`.`donor_id`;
drop view if exists donors_solicit_vw; create view donors_solicit_vw as select `donors`.`rotarian_id` AS `rotarian_id`,`donors`.`donor_id` AS `donor_id`,`donors`.`chamberid` AS `chamberid`,`donors`.`phone` AS `phone`,`donors`.`donor` AS `donor`,`donors`.`category` AS `category`,`donors`.`contact1` AS `contact1`,`donors`.`contact2` AS `contact2`,concat_ws('|',`donors`.`contact1`,`donors`.`contact2`) AS `contact`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`state` AS `state`,`donors`.`zip` AS `zip`,`donors`.`email` AS `email`,`donors`.`url` AS `url`,`donors`.`advertisement` AS `advertisement`,`donors`.`solicit` AS `solicit`,`donors`.`comments` AS `comments`,concat_ws(', ',`rotarians`.`lastname`,`rotarians`.`firstname`) AS `rotarian` from (`donors` left join `rotarians` on((`donors`.`rotarian_id` = `rotarians`.`rotarian_id`))) where solicit=1 group by `donors`.`donor_id`;
drop view if exists donors_vw; create view donors_vw as select `donors`.`rotarian_id` AS `rotarian_id`,`donors`.`donor_id` AS `donor_id`,`donors`.`chamberid` AS `chamberid`,`donors`.`phone` AS `phone`,`donors`.`donor` AS `donor`,`donors`.`category` AS `category`,`donors`.`contact1` AS `contact1`,`donors`.`contact2` AS `contact2`,concat_ws('|',`donors`.`contact1`,`donors`.`contact2`) AS `contact`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`state` AS `state`,`donors`.`zip` AS `zip`,`donors`.`email` AS `email`,`donors`.`url` AS `url`,`donors`.`advertisement` AS `advertisement`,`donors`.`solicit` AS `solicit`,`donors`.`comments` AS `comments`,concat_ws(', ',`rotarians`.`lastname`,`rotarians`.`firstname`) AS `rotarian` from `donors` left join `rotarians` on `donors`.`rotarian_id` = `rotarians`.`rotarian_id` group by `donors`.`donor_id`;
-- 
drop view if exists highbids_vw; create view highbids_vw as select `t1`.`bid_id` AS `highbid_id`,`t1`.`bidder_id` AS `highbidder_id`,if(isnull(`bidders`.`bidder`),'-',`bidders`.`bidder`) AS `highbidder`,`t1`.`item_id` AS `item_id`,`t1`.`bid` AS `highbid`,`t1`.`bidtime` AS `highbidtime`,timestampdiff(MINUTE,`t1`.`bidtime`,now()) AS `highbidage` from (((`bids` `t1` left join `bids` `t2` on(((`t1`.`item_id` = `t2`.`item_id`) and (`t1`.`bid` < `t2`.`bid`)))) join `bidders` on((`t1`.`bidder_id` = `bidders`.`bidder_id`))) join `items` on((`t1`.`item_id` = `items`.`item_id`))) where isnull(`t2`.`bid_id`);
-- 
drop view if exists items_current_vw; create view items_current_vw as select `items`.`item_id` AS `item_id`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from (`items_vw` `items` join `auctions_current_vw` `year` on((`items`.`year` = `year`.`year`)));
drop view if exists items_last_vw; create view items_last_vw as select `items`.`item_id` AS `item_id`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from (`items_vw` `items` join `auctions_current_vw` `year` on((`items`.`year` = (`year`.`year` - 1))));
drop view if exists items_recent_vw; create view items_recent_vw as select `items`.`item_id` AS `item_id`,`items`.`year` AS `year`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from (`items_vw` `items` join `auctions_current_vw` `year` on((`items`.`year` > (`year`.`year` - 3))));
drop view if exists items_vw; create view items_vw as select `items`.`item_id` AS `item_id`,`items`.`year` AS `year`,`items`.`donor_id` AS `donor_id`,`donors`.`donor` AS `donor`,`donors`.`url` AS `donorurl`,`items`.`number` AS `number`,`items`.`category` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`url` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`status`.`status` AS `status`,`items`.`notify` AS `notify`,`donors`.`advertisement` AS `advertisement`,if((`items`.`value` < 100),5,if((`items`.`value` < 250),30,50)) AS `startbid`,if(isnull(`highbids`.`highbid`),if((`items`.`value` < 100),5,if((`items`.`value` < 250),30,50)),if((`highbids`.`highbid` < `items`.`value`),(`highbids`.`highbid` + 5),(`highbids`.`highbid` + 1))) AS `minbid`,`highbids`.`highbidder_id` AS `highbidder_id`,if(isnull(`highbids`.`highbidder`),'-',`highbids`.`highbidder`) AS `highbidder`,`highbids`.`highbid` AS `highbid`,`highbids`.`highbidtime` AS `highbidtime`,`highbids`.`highbidage` AS `highbidage`,if((isnull(`items`.`timer`) or (`items`.`sold` is not null)),NULL,if((timestampdiff(MINUTE,`items`.`timer`,now()) > 5),1,0)) AS `cansell`,if((`highbids`.`highbid` >= `items`.`value`),1,NULL) AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,if(isnull(`items`.`timer`),NULL,timestampdiff(MINUTE,`items`.`timer`,now())) AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from (((`items` left join `donors` on((`items`.`donor_id` = `donors`.`donor_id`))) left join `highbids_vw` `highbids` on((`items`.`item_id` = `highbids`.`item_id`))) left join `items_vw_status_ss` `status` on((`items`.`item_id` = `status`.`item_id`)));
drop view if exists items_vw_bellringer_ss; create view items_vw_bellringer_ss as select `items`.`item_id` AS `item_id`,if((`highbids`.`highbid` >= `items`.`value`),1,NULL) AS `bellringer` from (`items` left join `highbids_vw` `highbids` on((`items`.`item_id` = `highbids`.`item_id`)));
drop view if exists items_vw_bids_ss; create view items_vw_bids_ss as select `items`.`item_id` AS `item_id`,if((`items`.`value` < 100),5,if((`items`.`value` < 250),30,50)) AS `startbid`,if(isnull(`highbids`.`highbid`),if((`items`.`value` < 100),5,if((`items`.`value` < 250),30,50)),if((`highbids`.`highbid` < `items`.`value`),(`highbids`.`highbid` + 5),(`highbids`.`highbid` + 1))) AS `minbid` from (`items` left join `highbids_vw` `highbids` on((`items`.`item_id` = `highbids`.`item_id`)));
drop view if exists items_vw_night_ss; create view items_vw_night_ss as select `items`.`item_id` AS `item_id`,`scheduled`.`night` AS `night` from (`items` join `auctions_vw` `scheduled` on((`items`.`scheduled` = cast(`scheduled`.`start` as date))));
drop view if exists items_vw_status_ss; create view items_vw_status_ss as select `items`.`item_id` AS `item_id`,if(((`items`.`scheduled` is not null) and isnull(`items`.`started`) and isnull(`items`.`sold`) and isnull(`items`.`cleared`) and isnull(`items`.`auctioneer`)),'Ready',if(((`items`.`scheduled` is not null) and isnull(`items`.`started`) and isnull(`items`.`sold`) and isnull(`items`.`cleared`) and isnull(`items`.`auctioneer`)),'Ready',if(((`items`.`scheduled` is not null) and isnull(`items`.`started`) and isnull(`items`.`sold`) and isnull(`items`.`cleared`) and (`items`.`auctioneer` is not null)),'OnDeck',if(((`items`.`scheduled` is not null) and (`items`.`started` is not null) and isnull(`items`.`sold`) and isnull(`items`.`cleared`) and (`items`.`auctioneer` is not null)),'Bidding',if(((`items`.`scheduled` is not null) and (`items`.`started` is not null) and (`items`.`sold` is not null) and isnull(`items`.`cleared`) and (`items`.`auctioneer` is not null)),'Sold',if(((`items`.`scheduled` is not null) and (`items`.`started` is not null) and (`items`.`sold` is not null) and (`items`.`cleared` is not null) and (`items`.`auctioneer` is not null)),'Complete',NULL)))))) AS `status` from `items`;
drop view if exists items_vw_timer_ss; create view items_vw_timer_ss as select `items`.`item_id` AS `item_id`,if(isnull(`items`.`timer`),NULL,timestampdiff(MINUTE,`items`.`timer`,now())) AS `timerminutes`,if((isnull(`items`.`timer`) or (`items`.`sold` is not null)),NULL,if((timestampdiff(MINUTE,`items`.`timer`,now()) > 5),1,0)) AS `cansell` from `items`;
-- 
-- # Remove year from these
-- # Use db aliases
-- manage_ads_vw				select `ads_vw`.`ad_id` AS `ad_id`,`ads_vw`.`year` AS `year`,`ads_vw`.`scheduled` AS `scheduled`,`ads_vw`.`advertiser_id` AS `advertiser_id`,if(`ads_vw`.`ad_id`,concat_ws(':',`ads_vw`.`advertiser`,`ads_vw`.`ad_id`),NULL) AS `advertiser`,`ads_vw`.`ad` AS `ad`,`ads_vw`.`adurl` AS `adurl` from `ads_vw` where (`ads_vw`.`year` = `auction_year`());
-- manage_bellitems_vw			select `bellitems_vw`.`bellitem_id` AS `bellitem_id`,`bellitems_vw`.`year` AS `year`,`bellitems_vw`.`bellitem` AS `bellitem` from `bellitems_vw` where (`bellitems_vw`.`year` = `auction_year`());
-- manage_donors_items_vw			select `donors_items_vw`.`donor_id` AS `donor_id`,`donors_items_vw`.`year` AS `year`,`donors_items_vw`.`sold` AS `sold`,`donors_items_vw`.`number` AS `number`,`donors_items_vw`.`item` AS `item`,`donors_items_vw`.`value` AS `value`,`donors_items_vw`.`highbid` AS `highbid`,`donors_items_vw`.`bellringer` AS `bellringer` from `donors_items_vw`;
-- manage_donors_vw			select `donors_vw`.`rotarian_id` AS `rotarian_id`,`donors_vw`.`donor_id` AS `donor_id`,`donors_vw`.`chamberid` AS `chamberid`,`donors_vw`.`phone` AS `phone`,`donors_vw`.`donor` AS `donor`,`donors_vw`.`category` AS `donorcat`,`donors_vw`.`contact1` AS `contact1`,`donors_vw`.`contact2` AS `contact2`,`donors_vw`.`contact` AS `contact`,`donors_vw`.`address` AS `address`,`donors_vw`.`city` AS `city`,`donors_vw`.`state` AS `state`,`donors_vw`.`zip` AS `zip`,`donors_vw`.`email` AS `email`,`donors_vw`.`url` AS `donorurl`,`donors_vw`.`advertisement` AS `advertisement`,`donors_vw`.`solicit` AS `solicit`,`donors_vw`.`comments` AS `comments`,`donors_vw`.`rotarian` AS `rotarian`,`DonorItemCountLastYear`.`items` AS `items` from (`donors_vw` left join `DonorItemCountLastYear` on((`donors_vw`.`donor_id` = `DonorItemCountLastYear`.`donor_id`)));
-- manage_items_vw				select `items_vw`.`item_id` AS `item_id`,`items_vw`.`year` AS `year`,`items_vw`.`number` AS `number`,`items_vw`.`itemcat` AS `itemcat`,`items_vw`.`item` AS `item`,`items_vw`.`description` AS `description`,`items_vw`.`value` AS `value`,`items_vw`.`itemurl` AS `itemurl`,`items_vw`.`donor_id` AS `donor_id`,`items_vw`.`advertisement` AS `advertisement`,if(`items_vw`.`donor_id`,concat_ws(':',`items_vw`.`donor`,`items_vw`.`donor_id`),NULL) AS `donor`,if(`items_vw`.`stockitem_id`,concat_ws(':',`items_vw`.`item`,`items_vw`.`stockitem_id`),NULL) AS `stockitem` from `items_vw` where (`items_vw`.`year` = `auction_year`());
-- manage_rotarians_vw			select `rotarians_vw`.`rotarian_id` AS `rotarian_id`,`rotarians_vw`.`rotarian` AS `rotarian` from `rotarians_vw`;
-- manage_stockitems_vw			select `stockitems_vw`.`stockitem_id` AS `stockitem_id`,`stockitems_vw`.`year` AS `year`,`stockitems_vw`.`itemcat` AS `itemcat`,`stockitems_vw`.`stockitem` AS `stockitem`,`stockitems_vw`.`value` AS `value`,`stockitems_vw`.`cost` AS `cost` from `stockitems_vw` where (`stockitems_vw`.`year` = `auction_year`());
-- 
drop view if exists nights_vw; create view nights_vw as select `items`.`item_id` AS `item_id`,if((`scheduled`.`night` = 0),NULL,`scheduled`.`night`) AS `scheduled`,if((`started`.`night` = 0),NULL,`started`.`night`) AS `started`,if((`timer`.`night` = 0),NULL,`timer`.`night`) AS `timer`,if((`sold`.`night` = 0),NULL,`sold`.`night`) AS `sold`,if((`cleared`.`night` = 0),NULL,`cleared`.`night`) AS `cleared`,if((`contacted`.`night` = 0),NULL,`contacted`.`night`) AS `contacted` from ((((((`items` left join `auctions_vw` `scheduled` on((`items`.`scheduled` = cast(`scheduled`.`start` as date)))) left join `auctions_vw` `started` on((`items`.`started` = cast(`started`.`start` as date)))) left join `auctions_vw` `timer` on((`items`.`timer` = cast(`timer`.`start` as date)))) left join `auctions_vw` `sold` on((`items`.`sold` = cast(`sold`.`start` as date)))) left join `auctions_vw` `cleared` on((`items`.`cleared` = cast(`cleared`.`start` as date)))) left join `auctions_vw` `contacted` on((`items`.`contacted` = cast(`contacted`.`start` as date))));
-- 
-- rotarian_compliance_vw			select `rc_vw_ss`.`year` AS `year`,`r`.`leader_id` AS `leader_id`,`l`.`lastname` AS `llastname`,`l`.`firstname` AS `lfirstname`,`r`.`rotarian_id` AS `rotarian_id`,`r`.`lastname` AS `rlastname`,`r`.`firstname` AS `rfirstname`,`r`.`lead` AS `lead`,`r`.`phone` AS `phone`,`r`.`email` AS `email`,if(isnull(`RotarianItemCountThisYear`.`items`),`rc_vw_ss`.`compliance`,if((`RotarianItemCountThisYear`.`items` >= 1),1,`rc_vw_ss`.`compliance`)) AS `compliance` from (((`rotarians` `r` join `rotarians` `l` on((`r`.`leader_id` = `l`.`rotarian_id`))) left join `rotarian_compliance_vw_ss` `rc_vw_ss` on((`rc_vw_ss`.`rotarian_id` = `r`.`rotarian_id`))) left join `RotarianItemCountThisYear` on((`RotarianItemCountThisYear`.`rotarian_id` = `r`.`rotarian_id`)));
-- rotarian_compliance_vw_ss		select `rc`.`rotarian_id` AS `rotarian_id`,`rc`.`year` AS `year`,`rc`.`compliance` AS `compliance` from `rotarian_compliance` `rc` join `auctions_current_vw` `year` on rc.year=year.year group by `rc`.`rotarian_id`,`rc`.`year`;
-- rotarians_vw				select `rotarians`.`rotarian_id` AS `rotarian_id`,`rotarians`.`lead` AS `lead`,`rotarians`.`lastname` AS `lastname`,`rotarians`.`firstname` AS `firstname`,concat(`rotarians`.`lastname`,', ',`rotarians`.`firstname`) AS `rotarian`,`rotarians`.`leader_id` AS `leader_id`,`rotarians`.`phone` AS `phone`,`rotarians`.`email` AS `email` from `rotarians`;
-- 
drop view if exists sales_current_vw; create view sales_current_vw as select `items`.`item_id` AS `item_id`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from `items_current_vw` `items` where (`items`.`sold` is not null);
drop view if exists sales_last_vw; create view sales_last_vw as select `items`.`item_id` AS `item_id`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from `items_last_vw` `items` where (`items`.`sold` is not null);
drop view if exists sales_recent_vw; create view sales_recent_vw as select `items`.`item_id` AS `item_id`,`items`.`year` AS `year`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from `items_recent_vw` `items` where (`items`.`sold` is not null);
drop view if exists sales_vw; create view sales_vw as select `items`.`item_id` AS `item_id`,`items`.`year` AS `year`,`items`.`donor_id` AS `donor_id`,`items`.`donor` AS `donor`,`items`.`donorurl` AS `donorurl`,`items`.`number` AS `number`,`items`.`itemcat` AS `itemcat`,`items`.`item` AS `item`,`items`.`stockitem_id` AS `stockitem_id`,`items`.`description` AS `description`,`items`.`itemurl` AS `itemurl`,`items`.`value` AS `value`,`items`.`auctioneer` AS `auctioneer`,`items`.`status` AS `status`,`items`.`notify` AS `notify`,`items`.`advertisement` AS `advertisement`,`items`.`startbid` AS `startbid`,`items`.`minbid` AS `minbid`,`items`.`highbidder_id` AS `highbidder_id`,`items`.`highbidder` AS `highbidder`,`items`.`highbid` AS `highbid`,`items`.`highbidtime` AS `highbidtime`,`items`.`highbidage` AS `highbidage`,`items`.`cansell` AS `cansell`,`items`.`bellringer` AS `bellringer`,`items`.`scheduled` AS `scheduled`,`items`.`seq` AS `seq`,`items`.`started` AS `started`,`items`.`timer` AS `timer`,`items`.`timerminutes` AS `timerminutes`,`items`.`sold` AS `sold`,`items`.`cleared` AS `cleared`,`items`.`contacted` AS `contacted` from `items_vw` `items` where (`items`.`sold` is not null);
-- 
-- schedule_ads_tablabels_vw		select `auctions`.`year` AS `year`,`auctions`.`night` AS `o`,concat(concat('Night ',`auctions`.`night`),' : ',if(isnull(`schedule_ads_tablabels_vw_ss`.`ad_id`),0,count(`schedule_ads_tablabels_vw_ss`.`ad_id`))) AS `label` from (`auctions` left join `schedule_ads_tablabels_vw_ss` on(((`auctions`.`year` = `schedule_ads_tablabels_vw_ss`.`year`) and (`auctions`.`night` = `schedule_ads_tablabels_vw_ss`.`night`)))) where (`auctions`.`year` = 2012) group by `auctions`.`night` union select `auction_year`() AS `year`,0 AS `o`,concat('All Nights : ',if(isnull(`ads_vw`.`ad_id`),0,count(`ads_vw`.`ad_id`))) AS `label` from `ads_vw` where ((`ads_vw`.`year` = `auction_year`()) and isnull(`ads_vw`.`scheduled`)) union select `auction_year`() AS `year`,9999 AS `o`,concat('All Ads : ',if(isnull(`ads_vw`.`ad_id`),0,count(`ads_vw`.`ad_id`))) AS `label` from `ads_vw` where (`ads_vw`.`year` = `auction_year`()) order by `o`;
-- schedule_ads_tablabels_vw_ss		select `ads_vw`.`year` AS `year`,if(isnull(`ads_vw`.`scheduled`),'All Nights',`ads_vw`.`scheduled`) AS `night`,`ads_vw`.`ad_id` AS `ad_id`,`ads_vw`.`scheduled` AS `scheduled` from `ads_vw`;
-- schedule_ads_vw				select `ads_vw`.`ad_id` AS `ad_id`,if(isnull(`ads_vw`.`scheduled`),0,`ads_vw`.`scheduled`) AS `scheduled`,concat(`ads_vw`.`advertiser`,' (',`ads_vw`.`ad`,')') AS `ad` from `ads_vw` where (`ads_vw`.`year` = `auction_year`()) order by if(isnull(`ads_vw`.`scheduled`),0,`ads_vw`.`scheduled`),`ads_vw`.`advertiser`;
-- 
-- sequence_items_tablabels_vw		select `auctions`.`year` AS `year`,`auctions`.`night` AS `o`,concat(concat('Night ',`auctions`.`night`),' : ',if(isnull(`sequence_items_tablabels_vw_ss`.`item_id`),0,count(`sequence_items_tablabels_vw_ss`.`item_id`)),' / $',format(if(isnull(`sequence_items_tablabels_vw_ss`.`value`),0,sum(`sequence_items_tablabels_vw_ss`.`value`)),2)) AS `label` from (`auctions` left join `sequence_items_tablabels_vw_ss` on(((`auctions`.`year` = `sequence_items_tablabels_vw_ss`.`year`) and (`auctions`.`night` = `sequence_items_tablabels_vw_ss`.`night`)))) where (`auctions`.`year` = 2012) group by `auctions`.`night` union select `auction_year`() AS `year`,0 AS `o`,concat('Not assigned : ',if(isnull(`items_vw`.`item_id`),0,count(`items_vw`.`item_id`)),' / $',format(if(isnull(`items_vw`.`value`),0,sum(`items_vw`.`value`)),2)) AS `label` from `items_vw` where ((`items_vw`.`year` = `auction_year`()) and isnull(`items_vw`.`scheduled`)) union select `auction_year`() AS `year`,9999 AS `o`,concat('All nights : ',if(isnull(`items_vw`.`item_id`),0,count(`items_vw`.`item_id`)),' / $',format(if(isnull(`items_vw`.`value`),0,sum(`items_vw`.`value`)),2)) AS `label` from `items_vw` where (`items_vw`.`year` = `auction_year`()) order by `o`;
-- sequence_items_tablabels_vw_ss		select `items_vw`.`year` AS `year`,if(isnull(`items_vw`.`scheduled`),'Not assigned',`items_vw`.`scheduled`) AS `night`,`items_vw`.`item_id` AS `item_id`,`items_vw`.`value` AS `value`,`items_vw`.`scheduled` AS `scheduled` from `items_vw`;
-- sequence_items_vw			select `items_vw`.`item_id` AS `item_id`,`items_vw`.`number` AS `number`,if(isnull(`items_vw`.`scheduled`),0,`items_vw`.`scheduled`) AS `scheduled`,`items_vw`.`seq` AS `seq`,concat(`items_vw`.`number`,' : ($',format(`items_vw`.`value`,2),') : ',`items_vw`.`item`,' (',`items_vw`.`donor`,')') AS `item` from `items_vw` where (`items_vw`.`year` = `auction_year`()) order by if(isnull(`items_vw`.`scheduled`),0,`items_vw`.`scheduled`),`items_vw`.`seq`,`items_vw`.`number`;
-- 
-- solicitationaids_compliance_vw		select concat(`rotarian_compliance_vw`.`llastname`,', ',`rotarian_compliance_vw`.`lfirstname`) AS `leader`,`rotarian_compliance_vw`.`rotarian_id` AS `rotarian_id`,concat(`rotarian_compliance_vw`.`rlastname`,', ',`rotarian_compliance_vw`.`rfirstname`) AS `rotarian`,`rotarian_compliance_vw`.`compliance` AS `compliance` from `rotarian_compliance_vw`;
-- solicitationaids_packet_vw		select concat(`rotarians`.`lastname`,', ',`rotarians`.`firstname`) AS `rotarian`,`rotarians`.`lead` AS `lead`,`donors`.`donor` AS `donor`,concat(' | ',`donors`.`contact1`,`donors`.`contact2`) AS `contact`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`phone` AS `phone`,`donors`.`email` AS `email`,`donors`.`advertisement` AS `advertisement`,`items_vw`.`year` AS `year`,`items_vw`.`number` AS `number`,`items_vw`.`item` AS `item`,`items_vw`.`value` AS `value`,`items_vw`.`highbid` AS `highbid`,if(`items_vw`.`bellringer`,'(BELLRINGER)','') AS `bellringer`,if(`items_vw`.`stockitem_id`,'(STOCKITEM)','') AS `stockitem` from ((`rotarians` left join `donors` on((`rotarians`.`rotarian_id` = `donors`.`rotarian_id`))) left join `items_vw` on((`donors`.`donor_id` = `items_vw`.`donor_id`))) where (((`items_vw`.`year` between (`auction_year`() - 3) and `auction_year`()) or isnull(`items_vw`.`item_id`)) and (`donors`.`solicit` = 1));
-- 
drop view if exists stockitems_current_vw; create view stockitems_current_vw as select `stockitems`.`stockitem_id` AS `stockitem_id`,`stockitems`.`itemcat` AS `itemcat`,`stockitems`.`stockitem` AS `stockitem`,`stockitems`.`value` AS `value`,`stockitems`.`cost` AS `cost` from (`stockitems_vw` `stockitems` join `auctions_current_vw` `year` on((`stockitems`.`year` = `year`.`year`)));
drop view if exists stockitems_vw; create view stockitems_vw as select `stockitems`.`stockitem_id` AS `stockitem_id`,`stockitems`.`year` AS `year`,`stockitems`.`category` AS `itemcat`,`stockitems`.`stockitem` AS `stockitem`,`stockitems`.`value` AS `value`,`stockitems`.`cost` AS `cost` from `stockitems`;
-- 
-- winners_current_vw
-- winners_last_vw
-- winners_recent_vw
-- winners_vw
-- 
drop view if exists xls_insert_vw; create view xls_insert_vw as select `scheduled`.`night` AS `night`,`items`.`number` AS `number`,`items`.`item` AS `item`,`items`.`value` AS `value`,`items`.`donor` AS `donor` from (`items_current_vw` `items` left join `auctions_vw` `scheduled` on((`items`.`scheduled` = cast(`scheduled`.`start` as date)))) order by `items`.`scheduled`,`items`.`number`;
drop view if exists xls_postcards_vw; create view xls_postcards_vw as select `donors`.`donor` AS `donor`,if((`donors`.`contact1` = `donors`.`donor`),'',`donors`.`contact1`) AS `contact1`,if((`donors`.`contact2` = `donors`.`contact1`),'',`donors`.`contact2`) AS `contact2`,`donors`.`address` AS `address`,`donors`.`city` AS `city`,`donors`.`state` AS `state`,`donors`.`zip` AS `zip` from `donors_solicit_vw` `donors`;
